### ISSUE TITLE
how to activate api

### ISSUE THREAD

**Issue by a7medee** [camenduru/stable-diffusion-webui-colab#1]
I'm getting this when using --api
![image](https://user-images.githubusercontent.com/112751092/199918061-d8c95ee8-c971-45be-9379-8b43aabffc9d.png)
note : I'm not programmer

**Comment by camenduru** [comment]
@a7medee maybe fixed, please try again

**Comment by a7medee** [comment]
still same

**Comment by camenduru** [comment]
```
This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "launch.py", line 252, in <module>
    start()
  File "launch.py", line 247, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 153, in webui
    create_api(app)
  File "/content/stable-diffusion-webui/webui.py", line 97, in create_api
    from modules.api.api import Api
  File "/content/stable-diffusion-webui/modules/api/api.py", line 9, in <module>
    from modules.api.models import *
  File "/content/stable-diffusion-webui/modules/api/models.py", line 194, in <module>
    class SamplerItem(BaseModel):
  File "/content/stable-diffusion-webui/modules/api/models.py", line 196, in SamplerItem
    aliases: list[str]  = Field(title="Aliases")
TypeError: 'type' object is not subscriptable
```

**Comment by camenduru** [comment]
```
Traceback (most recent call last):
  File "launch.py", line 252, in <module>
    start()
  File "launch.py", line 245, in start
    webui.api_only()
  File "/content/stable-diffusion-webui/webui.py", line 118, in api_only
    api = create_api(app)
  File "/content/stable-diffusion-webui/webui.py", line 97, in create_api
    from modules.api.api import Api
  File "/content/stable-diffusion-webui/modules/api/api.py", line 9, in <module>
    from modules.api.models import *
  File "/content/stable-diffusion-webui/modules/api/models.py", line 199, in <module>
    class UpscalerItem(BaseModel):
  File "/content/stable-diffusion-webui/modules/api/models.py", line 201, in UpscalerItem
    model_name: str | None = Field(title="Model Name")
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by camenduru** [comment]
https://github.com/tiangolo/typer/issues/371

**Comment by camenduru** [comment]
`from __future__ import annotations`

```
Traceback (most recent call last):
  File "launch.py", line 252, in <module>
    start()
  File "launch.py", line 245, in start
    webui.api_only()
  File "/content/stable-diffusion-webui/webui.py", line 118, in api_only
    api = create_api(app)
  File "/content/stable-diffusion-webui/webui.py", line 97, in create_api
    from modules.api.api import Api
  File "/content/stable-diffusion-webui/modules/api/api.py", line 10, in <module>
    from modules.api.models import *
  File "/content/stable-diffusion-webui/modules/api/models.py", line 200, in <module>
    class UpscalerItem(BaseModel):
  File "pydantic/main.py", line 179, in pydantic.main.ModelMetaclass.__new__
    self.test_dataloader = partial(self._test_dataloader, shuffle=shuffle_test_loader)
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    
  File "/usr/lib/python3.7/typing.py", line 263, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.7/typing.py", line 467, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by camenduru** [comment]
https://github.com/camenduru/stable-diffusion-webui/commit/7a2e36b583ef9eaefa44322e16faff6f9f1af169

**Comment by camenduru** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/7a2e36b583ef9eaefa44322e16faff6f9f1af169

**Comment by camenduru** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ebce0c57c78a3f22178e3a38938d19ec0dfb703d

**Comment by camenduru** [comment]
thanks to @aliencaocao --api now working 🎉
