### ISSUE TITLE
How about these smaller models for controlnet?

### ISSUE THREAD

**Issue by ForceConstant** [camenduru/stable-diffusion-webui-colab#101]
I stumbled upon these versions of the controlnet models which are much smaller. https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main If they work as well would be a good sub to the large ones the colab notebook downloads.

**Comment by camenduru** [comment]
Hi @ForceConstant 👋 please try this https://github.com/camenduru/stable-diffusion-webui-colab/blob/v2.0/control_net_webui_colab.ipynb

**Comment by ForceConstant** [comment]
It failed for me.
1. Loaded / Run colab
2. Goto Img2Img tab, 
3. Load a line sketch 512x512 I have
4. enable ControlNet, Procesor Canny, Model Canny.
5. Use guy and girl in text, hit generate.

```
  0% 0/16 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(o4l0o5j11cp5oqt)', 0, 'guy and girl', '', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x7FB3581EA880>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', True, 'canny', 'control_canny-fp16(e3fe7712)', 1, None, True, 'Scale to Fit (Inner Fit)', True, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/img2img.py", line 169, in img2img
    processed = process_images(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 628, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/content/stable-diffusion-webui/modules/processing.py", line 1044, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 302, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 221, in launch_sampling
    return func()
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 302, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 116, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 106, in forward2
    return forward(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 71, in forward
    control = outer.control_model(x=x, hint=outer.hint_cond, timesteps=timesteps, context=context)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 380, in forward
    hint = self.align(hint, h1 * 8, w1 * 8)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 368, in align
    c, h1, w1 = hint.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by camenduru** [comment]
is it working with Img2Img tab? I really don't know I test with text2image

**Comment by ForceConstant** [comment]
How does controlnet even work with text2img? Isn't the point of it is you start with an image or sketch and have it generate a new image?

**Comment by camenduru** [comment]
![Screenshot 2023-02-15 212722](https://user-images.githubusercontent.com/54370274/219119878-b39e9d03-6256-44b1-bcfd-20fbf9db27ca.jpg)
like this

**Comment by camenduru** [comment]
text2img ControlNet Tab

**Comment by ForceConstant** [comment]
doh, I didn't see that far down. Thanks. Works
