### ISSUE TITLE
Few Bugs

### ISSUE THREAD

**Issue by 7108** [camenduru/stable-diffusion-webui-colab#104]
After downloading the model from civitai browser when inclick on refresh models and then choose the model
It mostly fails to load and creates issue sometimes i've to restart the cell or sometimes the whole notebook

(+i think theres some issue with lorss too often they don't seems to be working or maybe I'm noob in loras)

But theres definitely a bug with zipping feature
While downloading the all the images created by zip option the downloading speed is terrible and mostly doesn't download if the file size is above 3-10mb (i request you to try with 64 mb)
I would have to download all the files manually on my slow pc

And yes if possible then use vae which works with all the models or an universal vae as the eyes comes horrible 90% of the time

_I'm sorry if i made it long or wrong with my limited knowledge but these are the bugs i found in these notebooks_

**Comment by etherealxx** [comment]
would be nice if you recreate the issue and post the screenshot of it (the error in the cell). The slow download is google colab's fault. You can instead connect with your google drive and use script to copy the outputs to your google drive. It is way faster.

You can download your own vae on the huggingface tab, using colab run command.

I'll check the civitai one though.

**Comment by etherealxx** [comment]
Hello @7108 , does the issue still exist?

**Comment by 7108** [comment]
I haven't encountered it since yesterday if it's fixed then thanks man

**Comment by 7108** [comment]
Will high res fix will get fixed in this version?

**Comment by 7108** [comment]
This is the best and easy to use stable diffusion collab i found 
Love you man you did some great work
(Bugs are mostly ignoreable for now)

**Comment by 7108** [comment]
New bug(loading bar dissappears)
Not sure why
Maybe automatic1111 bug
_sorry, i know im annoying_

**Comment by etherealxx** [comment]
> Will high res fix will get fixed in this version?

> New bug(loading bar dissappears) Not sure why Maybe automatic1111 bug

Those bugs are from gradio's side, not from this colab. Almost all webui colab has the same problem.

Though, for progress bar, v1.6 are pretty consistent. You should try that.

**Comment by 7108** [comment]
Thanks man i'm using that only but what about high res fix?
Will it get fixed as it don't seems to be working not showing high res steps

**Comment by etherealxx** [comment]
> Thanks man i'm using that only but what about high res fix? Will it get fixed as it don't seems to be working not showing high res steps

use upscale by 1.25 or 1.5 on 512x512 or 512x768 reso. Don't use past that.

**Comment by 7108** [comment]
That closing issue with checkpoint is still there, checkpoint dosnt load, few times

**Comment by 7108** [comment]
AttributeError: 'NoneType' object has no attribute 'sd_model_hash'

**Comment by etherealxx** [comment]
> That closing issue with checkpoint is still there, checkpoint dosnt load, few times

@7108 could you elaborate which version/branch did you use (main/v2.0), the model that you use, and the full copy of the log file since the `traceback`?

**Comment by 7108** [comment]
Main version
 model hashes...
0it [00:00, ?it/s]


This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Downloading models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.yaml:   0% 0.00/1.00G [00:00<?, ?B/s]Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai-api.py", line 49, in download_file
    response = requests.get(url, headers=headers, stream=True)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied

**Comment by 7108** [comment]
This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Downloading models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.yaml:   0% 0.00/1.00G [00:00<?, ?B/s]Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai-api.py", line 49, in download_file
    response = requests.get(url, headers=headers, stream=True)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.yaml successfully downloaded.
models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt successfully downloaded.
models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt successfully downloaded.
Calculating sha256 for /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt: d3582a026d6f9510cbc4bbc925b96226b02610ad6bf9ec44e55d2f63d34d1d04
Loading weights [d3582a026d] from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt
Error verifying pickled file from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 90, in check_pt
    with z.open(data_pkl_filenames[0]) as file:
  File "/usr/lib/python3.8/zipfile.py", line 1535, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/content/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, 'm'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


changing setting sd_model_checkpoint to Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt: AttributeError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/shared.py", line 554, in set
    self.data_labels[key].onchange()
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/webui.py", line 120, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 464, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 224, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

Loading weights [d3582a026d] from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt
Error verifying pickled file from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 90, in check_pt
    with z.open(data_pkl_filenames[0]) as file:
  File "/usr/lib/python3.8/zipfile.py", line 1535, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/content/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, 'm'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


changing setting sd_model_checkpoint to Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt: AttributeError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/shared.py", line 554, in set
    self.data_labels[key].onchange()
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/webui.py", line 120, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 464, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 224, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

Loading weights [d3582a026d] from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt
Error verifying pickled file from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 90, in check_pt
    with z.open(data_pkl_filenames[0]) as file:
  File "/usr/lib/python3.8/zipfile.py", line 1535, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/content/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, 'm'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


changing setting sd_model_checkpoint to Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt: AttributeError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/shared.py", line 554, in set
    self.data_labels[key].onchange()
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/webui.py", line 120, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 464, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 224, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

Loading weights [d3582a026d] from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt
Error verifying pickled file from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 90, in check_pt
    with z.open(data_pkl_filenames[0]) as file:
  File "/usr/lib/python3.8/zipfile.py", line 1535, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/content/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, 'm'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


changing setting sd_model_checkpoint to Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt: AttributeError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/shared.py", line 554, in set
    self.data_labels[key].onchange()
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/webui.py", line 120, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 464, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 224, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

Loading weights [d3582a026d] from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt
Error verifying pickled file from /content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 90, in check_pt
    with z.open(data_pkl_filenames[0]) as file:
  File "/usr/lib/python3.8/zipfile.py", line 1535, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/content/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, 'm'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


changing setting sd_model_checkpoint to Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.ckpt: AttributeError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/shared.py", line 554, in set
    self.data_labels[key].onchange()
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/webui.py", line 120, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 464, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 224, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by 7108** [comment]
The model is downlaoded and showing in files but it isnt loading

And sometimes showing error in red fonts

**Comment by etherealxx** [comment]
> Main version
> Its v2
Uhh which one, both?😅
And also, does this happen on all models or just that particular model?

**Comment by 7108** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/modules/ui.py", line 1646, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "/content/stable-diffusion-webui/modules/ui.py", line 1487, in run_settings_single
    if not opts.set(key, value):
  File "/content/stable-diffusion-webui/modules/shared.py", line 479, in set
    self.data_labels[key].onchange()
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/webui.py", line 64, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 344, in reload_model_weights
    load_model(checkpoint_info)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 292, in load_model
    sd_config = OmegaConf.load(checkpoint_info.config)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/omegaconf.py", line 188, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 173, in fetch_more_tokens
    return self.fetch_stream_end()
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 377, in fetch_stream_end
    self.remove_possible_simple_key()
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 318, in remove_possible_simple_key
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "/content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.yaml", line 71, column 1
could not find expected ':'
  in "/content/stable-diffusion-webui/models/Stable-diffusion/Uber_Realistic_Porn_Merge_URPM/uberRealisticPornMerge_urpmv12-inpainting.yaml", line 71, column 136






PS i was editing abs

**Comment by 7108** [comment]
I use encounter it in main version but tofay i encountered it in v2

**Comment by camenduru** [comment]
Hi @7108  👋 let's solve this in Discord. I'm confused about which one has been solved and which one hasn't. 🤪
