### ISSUE TITLE
Error while instaling extensions on Google Colab: AssertionError: extension access disabled because of command line flags

### ISSUE THREAD

**Issue by davidias244** [camenduru/stable-diffusion-webui-colab#18]
I'm getting this error when I try to install extensions in any of the Google Colab notebooks. Does anybody knows how to fix it?

```
Error completing request
Arguments: ('https://github.com/d8ahazard/sd_dreambooth_extension', ['ads', 'localization']) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/ui_extensions.py", line 153, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "/content/stable-diffusion-webui/modules/ui_extensions.py", line 117, in install_extension_from_url
    check_access()
  File "/content/stable-diffusion-webui/modules/ui_extensions.py", line 20, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags
```

**Comment by davidias244** [comment]
> Adding `--enable-insecure-extension-access` on the last line should fix it, and it should look like this:
> 
> ```
> !python launch.py --share --force-enable-xformers --enable-insecure-extension-access
> ```

Thanks for answering. Now it installed, but when I click Apply and Restart UI I get another error:

```
Closing server running on port: 7860
Reloading extensions
Reloading custom scripts
Error loading script: api.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 872, in _get_module
    """
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/feature_extraction_clip.py", line 18, in <module>
    from .image_processing_clip import CLIPImageProcessor
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/image_processing_clip.py", line 23, in <module>
    from ...image_processing_utils import BaseImageProcessor, BatchFeature, get_size_dict
  File "/usr/local/lib/python3.8/dist-packages/transformers/image_processing_utils.py", line 24, in <module>
    from .feature_extraction_utils import BatchFeature as BaseBatchFeature
  File "/usr/local/lib/python3.8/dist-packages/transformers/feature_extraction_utils.py", line 28, in <module>
    from .utils import (
ImportError: cannot import name 'cached_file' from 'transformers.utils' (/usr/local/lib/python3.8/dist-packages/transformers/utils/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
  File "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 16, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import reload_system_models, unload_system_models, printm, \
  File "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 12, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
  File "/usr/local/lib/python3.8/dist-packages/diffusers/__init__.py", line 39, in <module>
    from .pipelines import (
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/__init__.py", line 42, in <module>
    from .alt_diffusion import AltDiffusionImg2ImgPipeline, AltDiffusionPipeline
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/alt_diffusion/__init__.py", line 33, in <module>
    from .pipeline_alt_diffusion import AltDiffusionPipeline
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py", line 22, in <module>
    from transformers import CLIPFeatureExtractor, XLMRobertaTokenizer
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 863, in __getattr__
    Please note that you may need to restart your runtime after installation.
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 862, in __getattr__
    explained here: https://www.tensorflow.org/text/guide/tf_text_intro.
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 874, in _get_module
RuntimeError: Failed to import transformers.models.clip.feature_extraction_clip because of the following error (look up to see its traceback):
cannot import name 'cached_file' from 'transformers.utils' (/usr/local/lib/python3.8/dist-packages/transformers/utils/__init__.py)

Error loading script: main.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 872, in _get_module
    """
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/feature_extraction_clip.py", line 18, in <module>
    from .image_processing_clip import CLIPImageProcessor
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/image_processing_clip.py", line 23, in <module>
    from ...image_processing_utils import BaseImageProcessor, BatchFeature, get_size_dict
  File "/usr/local/lib/python3.8/dist-packages/transformers/image_processing_utils.py", line 24, in <module>
    from .feature_extraction_utils import BatchFeature as BaseBatchFeature
  File "/usr/local/lib/python3.8/dist-packages/transformers/feature_extraction_utils.py", line 28, in <module>
    from .utils import (
ImportError: cannot import name 'cached_file' from 'transformers.utils' (/usr/local/lib/python3.8/dist-packages/transformers/utils/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
  File "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 16, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import reload_system_models, unload_system_models, printm, \
  File "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 12, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
  File "/usr/local/lib/python3.8/dist-packages/diffusers/__init__.py", line 39, in <module>
    from .pipelines import (
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/__init__.py", line 42, in <module>
    from .alt_diffusion import AltDiffusionImg2ImgPipeline, AltDiffusionPipeline
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/alt_diffusion/__init__.py", line 33, in <module>
    from .pipeline_alt_diffusion import AltDiffusionPipeline
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py", line 22, in <module>
    from transformers import CLIPFeatureExtractor, XLMRobertaTokenizer
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 863, in __getattr__
    Please note that you may need to restart your runtime after installation.
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 862, in __getattr__
    explained here: https://www.tensorflow.org/text/guide/tf_text_intro.
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 874, in _get_module
RuntimeError: Failed to import transformers.models.clip.feature_extraction_clip because of the following error (look up to see its traceback):
cannot import name 'cached_file' from 'transformers.utils' (/usr/local/lib/python3.8/dist-packages/transformers/utils/__init__.py)
```

**Comment by camenduru** [comment]
thanks for the answer @NA-ID ❤ and hi @davidias244 I tried running `sd_dreambooth_extension ` on colab even you fix all errors you are hitting the memory limit some how if you need dreambooth please try this [this ](https://github.com/camenduru/stable-diffusion-dreambooth-colab/blob/main/stable-diffusion-dreambooth_colab.ipynb)

**Comment by davidias244** [comment]
> thanks for the answer @NA-ID ❤ and hi @davidias244 I tried running `sd_dreambooth_extension ` on colab even you fix all errors you are hitting the memory limit some how if you need dreambooth please try this [this ](https://github.com/camenduru/stable-diffusion-dreambooth-colab/blob/main/stable-diffusion-dreambooth_colab.ipynb)

Ok man, thank you for aswering. I will do that!
