### ISSUE TITLE
[Kaggle Bug]: can't install sd_dreambooth_extension

### ISSUE THREAD

**Issue by Asmedeus998** [camenduru/stable-diffusion-webui-colab#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

using latest `stable-diffusion-webui-kaggle`

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What happened?

I try to install sd_dreambooth_extension via GUI / git clone both fail.

### Console logs

```Shell
Restarting UI...
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Error loading script: api.py
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/kaggle/working/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/kaggle/working/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 25, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.diff_to_sd import compile_checkpoint
  File "/kaggle/working/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 16, in <module>
    from diffusers import DiffusionPipeline
ModuleNotFoundError: No module named 'diffusers'

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/kaggle/working/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/kaggle/working/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 13, in <module>
    from diffusers.utils import logging as dl
ModuleNotFoundError: No module named 'diffusers'

Error loading script: main.py
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/kaggle/working/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/kaggle/working/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 8, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_webhook import save_and_test_webhook
  File "/kaggle/working/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_webhook.py", line 9, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'
```

**Comment by camenduru** [comment]
Hi @Asmedeus998 👋 I am preparing to support this plugin https://github.com/ddPn08/kohya-sd-scripts-webui
I will look at `sd_dreambooth_extension` for an alternative

please join this https://discord.gg/pdh69hs8cX discord from https://github.com/d8ahazard/sd_dreambooth_extension/wiki 
you will see a `google-colab` channel people trying like you and tell us if it works 🥳
