### ISSUE TITLE
[Bug]: Eimis notebook + ControlNet in segmentation mode == python error

### ISSUE THREAD

**Issue by IPv6** [camenduru/stable-diffusion-webui-colab#220]
### What happened?

I`m using this notebook: https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/v2.0/eimis_anime_diffusion_1_webui_colab.ipynb with settings like here: 
<img width="938" alt="Screenshot 2023-03-04 at 19 19 48" src="https://user-images.githubusercontent.com/40495/222917031-e3ce97c5-bf34-471e-bd72-155e324d27c9.png">

and getting python KeyError. Other modes work ok

### Console logs

```Shell
Loading model: control_seg-fp16 [b9c1cc12]
Loaded state_dict from [/content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_seg-fp16.safetensors]
ControlNet model control_seg-fp16 [b9c1cc12] loaded.
Loading preprocessor: segmentation
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 657, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 157, in uniformer
    result = model_uniformer(img)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/__init__.py", line 33, in apply_uniformer
    model = init_segmentor(config_file, modelpath)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/inference.py", line 31, in init_segmentor
    config = mmcv.Config.fromfile(config)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mmpkg/mmcv/utils/config.py", line 334, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mmpkg/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/uniformer.py", line 247, in <module>
    class UniFormer(nn.Module):
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mmpkg/mmcv/utils/registry.py", line 311, in _register
    self._register_module(
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mmpkg/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'UniFormer is already registered in models'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

eimis_anime_diffusion_1

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

**Comment by machiavel23** [comment]
Yes, it's a bug from the extension itself. https://discord.com/channels/1077510466470952990/1081588055007297576

I thought it was solved by the author tho, did it just happened?

**Comment by IPv6** [comment]
@machiavel23 yes, experienced it like an hour ago, notebook was loaded 2h-3h ago (so this is with fresh git content, i suppose)

**Comment by camenduru** [comment]
thanks for the info @IPv6 ❤it is working now 🥳
