### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pop'

### ISSUE THREAD

**Issue by SiTu1O** [camenduru/stable-diffusion-webui-colab#24]
Traceback (most recent call last):
  File "launch.py", line 295, in <module>
    start()
  File "launch.py", line 290, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 133, in webui
    initialize()
  File "/content/stable-diffusion-webui/webui.py", line 63, in initialize
    modules.sd_models.load_model()
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 313, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 196, in load_model_weights
    sd = read_state_dict(checkpoint_file)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 178, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 152, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by camenduru** [comment]
which notebook is this?
