### ISSUE TITLE
[Bug]: Kaggle embeddings dont work at all

### ISSUE THREAD

**Issue by nevo993** [camenduru/stable-diffusion-webui-colab#243]
### What happened?

Hey tried to pull some embeddings by using that:
`!wget -O /kaggle/working/stable-diffusion-webui/embeddings/bad_prompt.pt -L https://huggingface.co/Nevo399/c1/blob/main/bad_prompt.pt`
output was `--2023-03-08 11:02:21--  https://huggingface.co/Nevo399/c1/blob/main/EasyNegative.safetensors
Resolving huggingface.co (huggingface.co)... 3.231.67.228, 54.235.118.239, 2600:1f18:147f:e850:e203:c458:10cd:fc3c, ...
Connecting to huggingface.co (huggingface.co)|3.231.67.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37179 (36K) [text/html]
Saving to: ‘/kaggle/working/stable-diffusion-webui/embeddings/EasyNegative.safetensors’
` so all good.
Did it just after first code is done and recieved error like console log. After that i was digging a bit for solution and i found [this post](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3968#issuecomment-1308485736) but didnt helped, that was helping people which was doing it on desktop pc, and not on kaggle... Also tried add embeddings on other versions which people made on kaggle and its still same error. Google colab works fine and there is no issue but on kaggle is. 
If someone who knows whats wrong please help...

### Console logs

```Shell
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI


Launching Web UI with arguments: --share --xformers --enable-insecure-extension-access --theme dark --gradio-queue
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Loading weights [a504b5b137] from /kaggle/working/stable-diffusion-webui/models/Stable-diffusion/anything-v4.5-vae-swapped.safetensors
Creating model from config: /kaggle/working/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Error verifying pickled file from /kaggle/working/stable-diffusion-webui/embeddings/bad_prompt.pt:
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/opt/conda/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/opt/conda/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/kaggle/working/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, '<'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error loading embedding bad_prompt.pt:
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/kaggle/working/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 164, in load_from_file
    if 'string_to_param' in data:
TypeError: argument of type 'NoneType' is not iterable

Error verifying pickled file from /kaggle/working/stable-diffusion-webui/embeddings/EasyNegative.pt:
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/opt/conda/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/opt/conda/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/kaggle/working/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, '<'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error loading embedding EasyNegative.pt:
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/kaggle/working/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 164, in load_from_file
    if 'string_to_param' in data:
TypeError: argument of type 'NoneType' is not iterable

Error loading embedding EasyNegative.safetensors:
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/kaggle/working/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 159, in load_from_file
    data = safetensors.torch.load_file(path, device="cpu")
  File "/opt/conda/lib/python3.7/site-packages/safetensors/torch.py", line 98, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
Exception: Error while deserializing header: HeaderTooLarge

Textual inversion embeddings loaded(0): 
Model loaded in 6.7s (create model: 5.3s, apply weights to model: 1.3s).
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

https://www.kaggle.com/code/camenduru/stable-diffusion-webui-kaggle

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by nevo993** [comment]
sorry fixed issue by downloading embeddings from original source, not from my copied files, dont know why but it worked.
