### ISSUE TITLE
v2.0 version ，load lora fail

### ISSUE THREAD

**Issue by zhoujinjin1** [camenduru/stable-diffusion-webui-colab#244]
Total progress:   0% 0/20 [00:00<?, ?it/s]activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7efb752cf3a0>]: RuntimeError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 151, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 83, in load_lora
    sd = sd_models.read_state_dict(filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 217, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[128, 1280, 1, 1]' is invalid for input of size 4821

**Comment by zhoujinjin1** [comment]
load koreanDollLikeness_v10.safetensors fail。。。。。。

**Comment by camenduru** [comment]
Hi @zhoujinjin1 👋 please send your colab and model link

**Comment by sulmz** [comment]
I face the same question, the same lora in online webui is failed, but in my m1 mac is ok.

**Comment by zhoujinjin1** [comment]
> 
if your big model is sd，you will face this question，but if your big model is chillout，there won't have this error

**Comment by sulmz** [comment]
My big model is chillout, and lora is taiwan,japanese,korean doll likeness,
also happen. But my mac use the same model is not happen, my m1 mac

ZhouJinHao ***@***.***> 于2023年3月15日周三 09:37写道：

**Comment by camenduru** [comment]
please try those models

https://huggingface.co/aimainia/koreanDollLikeness_v10/blob/main/koreanDollLikeness_v10.safetensors
https://huggingface.co/amornlnw7/koreanDollLikeness_v15/blob/main/koreanDollLikeness_v15.safetensors
https://huggingface.co/LittleJuliet/koreanDollLikeness/blob/main/koreanDollLikeness.safetensors
https://huggingface.co/opsopus/koreanDollLikeness/blob/main/kdllora_v15.safetensors
