### ISSUE TITLE
train_network.py

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#248]
```py
Traceback (most recent call last):
  File "/content/trainer/sd-scripts/train_network.py", line 642, in <module>
    train(args)
  File "/content/trainer/sd-scripts/train_network.py", line 503, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_condition.py", line 580, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_blocks.py", line 837, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 291, in forward
    attn_output = self.attn1(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward_xformers() got an unexpected keyword argument 'encoder_hidden_states'
```

**Comment by camenduru** [comment]
https://github.com/kohya-ss/sd-scripts/blob/main/train_network.py

**Comment by camenduru** [comment]
fixed
