### ISSUE TITLE
[Bug]: ValueError(f"no metadata / メタデータファイルがありません: {subset.metadata_file}")

### ISSUE THREAD

**Issue by stark-eth** [camenduru/stable-diffusion-webui-colab#254]
### What happened?

Train with captions.
Traceback (most recent call last):
  File "/content/sd-scripts/train_network.py", line 642, in <module>
    train(args)
  File "/content/sd-scripts/train_network.py", line 93, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "/content/sd-scripts/library/config_util.py", line 370, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "/content/sd-scripts/library/train_util.py", line 897, in __init__
    raise ValueError(f"no metadata / メタデータファイルがありません: {subset.metadata_file}")
ValueError: no metadata / メタデータファイルがありません: /content/drive/MyDrive/AI/training/parkminyoung/parkminyoung-latents.json
mv: cannot stat '/content/parkminyoung/last.safetensors': No such file or directory

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

colab

### Which repo branch did the colab you use comes from ?

training

### Which tunnel did you use ?

--googleusercontent

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
Hi @stark-eth please watch this https://www.youtube.com/watch?v=bt0tEVgiAf4

**Comment by zizh01** [comment]
> ### What happened?
> Train with captions. Traceback (most recent call last): File "/content/sd-scripts/train_network.py", line 642, in train(args) File "/content/sd-scripts/train_network.py", line 93, in train train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group) File "/content/sd-scripts/library/config_util.py", line 370, in generate_dataset_group_by_blueprint dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params)) File "/content/sd-scripts/library/train_util.py", line 897, in **init** raise ValueError(f"no metadata / メタデータファイルがありません: {subset.metadata_file}") ValueError: no metadata / メタデータファイルがありません: /content/drive/MyDrive/AI/training/parkminyoung/parkminyoung-latents.json mv: cannot stat '/content/parkminyoung/last.safetensors': No such file or directory
> 
> ### Console logs
> _No response_
> 
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and checked the recent builds/commits
> 
> ### Are you using the latest version of the colab notebook?
> * [x]  Yes, i am using the latest version from the repo
> 
> ### Which colab notebook did you use?
> colab
> 
> ### Which repo branch did the colab you use comes from ?
> training
> 
> ### Which tunnel did you use ?
> --googleusercontent
> 
> ### What browsers do you use to access the WebUI ?
> Google Chrome

Hi, I'm also troubled with the same issue, have you found a solution?

**Comment by camenduru** [comment]
Hi @zizh01  please try this ![image](https://user-images.githubusercontent.com/54370274/225512396-dedb1434-f660-4695-befd-298c7e0dc0eb.png)

can you see .json files in your folder like this
![Screenshot_2023-03-15_045817](https://user-images.githubusercontent.com/54370274/225512544-74fabbf0-d853-4b47-bb91-374b03616e6a.png)

**Comment by zizh01** [comment]
@camendur
Hi, thks for your quick reply!

Actually, when i use the default 'ACertainty.ckpt' model, it works well. But, when it is turned to other models, e.g., moDi-'v1-pruned.ckpt', the error occurs. I also found another _pickle.UnpicklingError before this valueerro, as shown below:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/127828656/225529465-32b10572-2f09-4405-a968-332b3937cde9.png">

I can see .json files in the folder, following the provided image, I modify the extension, but it seems did not work for me.

**Comment by zizh01** [comment]
@camenduru 
Hi! thks for your quick reply!

Actually, when I use the default 'ACertainty.ckpt' in your colab notebook, it works well. But the error occurs when I try to switch to other models, e.g.,  'moDi-v1-pruned.ckpt' (see the following pic)
<img width="818" alt="image" src="https://user-images.githubusercontent.com/127828656/225530898-f4749eb8-3405-4460-b33e-7f9bd1d9e56f.png">
Before this 'ValueError', there is another 'UnpicklingError', as present below:
`load VAE: /content/model/moDi-v1-pruned.ckpt
Traceback (most recent call last):
  File "/content/sd-scripts/finetune/prepare_buckets_latents.py", line 261, in <module>
    main(args)
  File "/content/sd-scripts/finetune/prepare_buckets_latents.py", line 76, in main
    vae = model_util.load_vae(args.model_name_or_path, weight_dtype)
  File "/usr/local/lib/python3.9/dist-packages/library/model_util.py", line 1112, in load_vae
    else torch.load(vae_id, map_location="cpu"))
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
2023-03-16 05:21:11.136637: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-16 05:21:11.316232: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-16 05:21:12.071780: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-16 05:21:12.071888: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-16 05:21:12.071907: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
Downloading (…)olve/main/vocab.json: 100% 961k/961k [00:00<00:00, 6.78MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 4.73MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 82.2kB/s]
Downloading (…)okenizer_config.json: 100% 905/905 [00:00<00:00, 204kB/s]
Train with captions.
Traceback (most recent call last):
  File "/content/sd-scripts/train_network.py", line 642, in <module>
    train(args)
  File "/content/sd-scripts/train_network.py", line 93, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "/content/sd-scripts/library/config_util.py", line 370, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "/content/sd-scripts/library/train_util.py", line 897, in __init__
    raise ValueError(f"no metadata / メタデータファイルがありません: {subset.metadata_file}")
ValueError: no metadata / メタデータファイルがありません: /content ........`

the .json files are just in the folder, and I try the solution provided, but it seems did not work for me : (
