### ISSUE TITLE
[Bug]: Gradio gets a ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by BunE-exe** [camenduru/stable-diffusion-webui-colab#261]
### What happened?

ERROR:    Exception in ASGI application

### Console logs

```Shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 436, in join_queue
    session_info = await websocket.receive_json()
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

abyss_orange_mix_3_webui_colab

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by etherealxx** [comment]
what were you doing before this error happened? generating stuff? txt2img? img2img?

**Comment by BunE-exe** [comment]
img2img, or any options in that tab.

**Comment by etherealxx** [comment]
for img2img, maybe decrease the resolution a little bit. For png info, use [this extension](https://github.com/NoCrypt/sd-fast-pnginfo).
We'll figure out the problem soon.

**Comment by camenduru** [comment]
thanks for the info @BunE-exe ❤ gradio fixed connection error

**Comment by bport98** [comment]
In mi case I'm facing the same error!

**Comment by camenduru** [comment]
@blackpro98

**Comment by camenduru** [comment]
Hi @blackpro98 👋 please tell me  which type of colab is giving you the error `lite` `stable` or `nightly` ?
