### ISSUE TITLE
[Bug]: Unable to enter Gradio

### ISSUE THREAD

**Issue by BunE-exe** [camenduru/stable-diffusion-webui-colab#269]
### What happened?

After executing the notebook of abyss orange mix 3 and laucnhing the public url the site loads then says "504 Gateway Time-out"

### Console logs

```Shell
Error executing callback ui_tabs_callback for /content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 194, in on_ui_tabs
    components = deforum_args.setup_deforum_setting_dictionary(None, True, True)
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/args.py", line 688, in setup_deforum_setting_dictionary
    controlnet_dict = setup_controlnet_ui()
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/deforum_controlnet.py", line 170, in setup_controlnet_ui
    return setup_controlnet_ui_raw()
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/deforum_controlnet.py", line 72, in setup_controlnet_ui_raw
    from scripts.controlnet import update_cn_models, cn_models, cn_models_names
ImportError: cannot import name 'update_cn_models' from 'scripts.controlnet' (/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

[stable] abyss_orange_mix_3_webui_colab 

### Which repo branch did the colab you use comes from ?

stable

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by etherealxx** [comment]
yes this also happens on my colab. I think the problem is on the gradio side.

**Comment by camenduru** [comment]
thanks for the info @BunE-exe ❤ gradio fixed
