### ISSUE TITLE
Deforum ImportError: cannot import name 'update_cn_models' from 'scripts.controlnet'

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#288]
```py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 189, in on_ui_tabs
    components = deforum_args.setup_deforum_setting_dictionary(None, True, True)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/args.py", line 683, in setup_deforum_setting_dictionary
    controlnet_dict = setup_controlnet_ui()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/deforum_controlnet.py", line 171, in setup_controlnet_ui
    return setup_controlnet_ui_raw()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/deforum_controlnet.py", line 73, in setup_controlnet_ui_raw
    from scripts.controlnet import update_cn_models, cn_models, cn_models_names
ImportError: cannot import name 'update_cn_models' from 'scripts.controlnet' (/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py)
```

**Comment by camenduru** [comment]
reset --hard

**Comment by dafu-wu** [comment]
the problem still exists
