### ISSUE TITLE
[Bug]: Error installing xformers

### ISSUE THREAD

**Issue by L134139** [camenduru/stable-diffusion-webui-colab#308]
### What happened?

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused --multiple
2023-03-21 02:39:25.320406: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-21 02:39:27.947888: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-21 02:39:27.948111: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-21 02:39:27.948141: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[AddNet] Updating model hashes...
100% 10/10 [00:00<00:00, 2031.93it/s]
[AddNet] Updating model hashes...
100% 10/10 [00:00<00:00, 2341.22it/s]
all detected, remote.moe trying to connect...
all detected, cloudflared trying to connect...
Error loading script: convert_original_stable_diffusion_to_diffusers.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/stable-diffusion-vid2vid/scripts/convert_original_stable_diffusion_to_diffusers.py", line 19, in <module>
    from diffusers.pipelines.stable_diffusion.convert_from_ckpt import load_pipeline_from_original_stable_diffusion_ckpt
ModuleNotFoundError: No module named 'diffusers'
![1](https://user-images.githubusercontent.com/51356527/226506659-0a11c9de-37c1-4165-884c-56546b3b4e71.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

then type '7th layer

### Which repo branch did the colab you use comes from ?

drive

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by etherealxx** [comment]
hello, do you use the latest colab from the repo? check it out, it's already updated. Tell me again if the solution doesn't works

**Comment by L134139** [comment]
Yes, I'm using the latest version, but I still get the same error







许多
***@***.***







                       
Original Email
                       
                     

Sender:"Etherealxx"< ***@***.*** &gt;;

Sent Time:2023/3/21 3:58

To:"camenduru/stable-diffusion-webui-colab"< ***@***.*** &gt;;

Cc recipient:"L134139"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [camenduru/stable-diffusion-webui-colab] [Bug]: Error installingxformers (Issue #308)




 
hello, do you use the latest colab from the repo? check it out, it's already updated. Tell me again if the solution doesn't works

**Comment by basedholychad** [comment]
same problem, maybe try using old code and wait till they fix this new branches

**Comment by L134139** [comment]
> ### What happened?
> Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused --multiple 2023-03-21 02:39:25.320406: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 AVX512F FMA To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. 2023-03-21 02:39:27.947888: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia 2023-03-21 02:39:27.948111: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia 2023-03-21 02:39:27.948141: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly. [AddNet] Updating model hashes... 100% 10/10 [00:00<00:00, 2031.93it/s] [AddNet] Updating model hashes... 100% 10/10 [00:00<00:00, 2341.22it/s] all detected, remote.moe trying to connect... all detected, cloudflared trying to connect... Error loading script: convert_original_stable_diffusion_to_diffusers.py Traceback (most recent call last): File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module module_spec.loader.exec_module(module) File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/stable-diffusion-vid2vid/scripts/convert_original_stable_diffusion_to_diffusers.py", line 19, in from diffusers.pipelines.stable_diffusion.convert_from_ckpt import load_pipeline_from_original_stable_diffusion_ckpt ModuleNotFoundError: No module named 'diffusers' ![1](https://user-images.githubusercontent.com/51356527/226506659-0a11c9de-37c1-4165-884c-56546b3b4e71.png)
> 
> ### Console logs
> _No response_
> 
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and checked the recent builds/commits
> 
> ### Are you using the latest version of the colab notebook?
> * [x]  Yes, i am using the latest version from the repo
> 
> ### Which colab notebook did you use?
> then type '7th layer
> 
> ### Which repo branch did the colab you use comes from ?
> drive
> 
> ### Which tunnel did you use ?
> --cloudflared
> 
> ### What browsers do you use to access the WebUI ?
> Go
![04](https://user-images.githubusercontent.com/51356527/226517137-85954f71-3677-4358-88d1-88fa475f6387.png)
ogle Chrome

**Comment by camenduru** [comment]
Hi @L134139 👋 please delete this extension stable-diffusion-vid2vid maybe works

**Comment by camenduru** [comment]
Hi @basedholychad 👋 are you also using` stable-diffusion-vid2vid` extension
