### ISSUE TITLE
[Bug]: simple_lora_trainer.ipynb can't running

### ISSUE THREAD

**Issue by stephonye** [camenduru/stable-diffusion-webui-colab#315]
### What happened?

Traceback (most recent call last):
  File "/content/sd-scripts/train_network.py", line 642, in <module>
    train(args)
  File "/content/sd-scripts/train_network.py", line 122, in train
    train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers)
  File "/content/sd-scripts/library/train_util.py", line 1397, in replace_unet_modules
    replace_unet_cross_attn_to_xformers()
  File "/content/sd-scripts/library/train_util.py", line 1445, in replace_unet_cross_attn_to_xformers
    raise ImportError("No xformers / xformersがインストールされていないようです")
ImportError: No xformers / xformersがインストールされていないようです
mv: cannot stat '/content/gaggirl_v1/last.safetensors': No such file or directory

### Console logs

```Shell
Traceback (most recent call last):
  File "/content/sd-scripts/train_network.py", line 642, in <module>
    train(args)
  File "/content/sd-scripts/train_network.py", line 122, in train
    train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers)
  File "/content/sd-scripts/library/train_util.py", line 1397, in replace_unet_modules
    replace_unet_cross_attn_to_xformers()
  File "/content/sd-scripts/library/train_util.py", line 1445, in replace_unet_cross_attn_to_xformers
    raise ImportError("No xformers / xformersがインストールされていないようです")
ImportError: No xformers / xformersがインストールされていないようです
mv: cannot stat '/content/gaggirl_v1/last.safetensors': No such file or directory
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

simple_lora_trainer

### Which repo branch did the colab you use comes from ?

training

### Which tunnel did you use ?

--multiple

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by moyuyu203** [comment]
It seems like you didn't install xformers.
Try add this line: !pip install -q xformers==0.0.16

**Comment by stephonye** [comment]
> It seems like you didn't install xformers. Try add this line: !pip install -q xformers==0.0.16

Thanks for your reply, I actually executed this:
!pip install -q --pre xformers==0.0.17.dev476 -U

**Comment by camenduru** [comment]
Hi @stephonye 👋 Thanks for the info ♥️ please try again

**Comment by stephonye** [comment]
> Hi @stephonye 👋 Thanks for the info ♥️ please try again

Lot of thanks！
