### ISSUE TITLE
[Bug]: trying to get list from Civitai but meet error

### ISSUE THREAD

**Issue by ningolus** [camenduru/stable-diffusion-webui-colab#316]
### What happened?

![Uploading image.png…]()
Hi, firstly thank you very much for enabling such convenient tool on colab. Really appreciated and really happy when i saw my first pic.
Met a problem today that, I was trying to get list from Civitai but failed, dunno why, restarting is not resolving the problem, nor did upgrating to newest version. please see the screenshon here:

### Console logs

```Shell
Request failed with status code: 400
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai-api.py", line 197, in update_model_list
    json_data = api_to_data(content_type, sort_type, use_search_term, search_term)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai-api.py", line 167, in api_to_data
    return request_civit_api(f"{api_url}&types={content_type}&sort={sort_type}")
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai-api.py", line 282, in request_civit_api
    exit()
  File "/usr/lib/python3.9/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

run.ipynb

### Which repo branch did the colab you use comes from ?

drive

### Which tunnel did you use ?

--multiple

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by ningolus** [comment]
![Uploading capture.PNG…]()
sorry some how i couldn't upload the 160kb PNG screenshot, but basically it's a red error in "model" and "version" under CivitAi page

**Comment by etherealxx** [comment]
Have you tried that again now? Maybe it's has something to do with civitai server state on that moment

**Comment by Nicholls01** [comment]
> 

tried, still the same

**Comment by etherealxx** [comment]
@Nicholls01 CivitAI website is currently on outage. Please wait for several hours. I'll report to you later.

**Comment by Nicholls01** [comment]
> @Nicholls01 CivitAI website is currently on outage. Please wait for several hours. I'll report to you later.

Thank you! I'll wait for its back and see

**Comment by Nicholls01** [comment]
> @Nicholls01 CivitAI website is currently on outage. Please wait for several hours. I'll report to you later.

Hi CivitAI is back but the issue still exists

**Comment by etherealxx** [comment]
have you tried again now? like, right now? Or, if you want to download models, you can use batchlinks instead.

**Comment by Nicholls01** [comment]
> have you tried again now? like, right now? Or, if you want to download models, you can use batchlinks instead.

yes tried right now the same problem

**Comment by camenduru** [comment]
Hi @Nicholls01 👋 Hi @ningolus 👋 please first use `One Time Install & Update` colab

**Comment by Nicholls01** [comment]
> Hi @Nicholls01 👋 Hi @ningolus 👋 please first use `One Time Install & Update` colab
Thanks! Resolved after undate. please mark this issue as resolved (ningolus is also me)

**Comment by TheWaterGlass** [comment]
Hello, I'm having the same issues, but I don't know what is the One time Install & Update colab. Could someone help me?
