### ISSUE TITLE
PyTorch 2.0

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#333]
### What happened?

PyTorch 2.0

### Console logs

```shell
Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 356, in <module>
    start()
  File "/content/stable-diffusion-webui/launch.py", line 347, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 21, in <module>
    import pytorch_lightning # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities.imports import _SCIPY_AVAILABLE
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/utilities/__init__.py", line 1, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.utilities.data import select_topk, to_onehot
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/utilities/data.py", line 19, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/utilities/imports.py", line 112, in <module>
    _TORCHVISION_GREATER_EQUAL_0_8: Optional[bool] = _compare_version("torchvision", operator.ge, "0.8.0")
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/utilities/imports.py", line 78, in _compare_version
    if not _module_available(package):
  File "/usr/local/lib/python3.9/dist-packages/torchmetrics/utilities/imports.py", line 59, in _module_available
    module = import_module(module_names[0])
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/dist-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/usr/local/lib/python3.9/dist-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/usr/local/lib/python3.9/dist-packages/torchvision/datasets/_optical_flow.py", line 12, in <module>
    from ..io.image import _read_png_16
  File "/usr/local/lib/python3.9/dist-packages/torchvision/io/__init__.py", line 8, in <module>
    from ._load_gpu_decoder import _HAS_GPU_VIDEO_DECODER
  File "/usr/local/lib/python3.9/dist-packages/torchvision/io/_load_gpu_decoder.py", line 1, in <module>
    from ..extension import _load_library
  File "/usr/local/lib/python3.9/dist-packages/torchvision/extension.py", line 107, in <module>
    _check_cuda_version()
  File "/usr/local/lib/python3.9/dist-packages/torchvision/extension.py", line 80, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
```

### Which repo branch did the colab you use comes from ?

I don't know

### Which tunnel did you use ?

--multiple

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
![image](https://user-images.githubusercontent.com/54370274/229594349-0c9d098f-b807-41bc-a2fc-8422565a3092.png)

**Comment by camenduru** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.

**Comment by camenduru** [comment]
![image](https://user-images.githubusercontent.com/54370274/229597458-283c85a4-2b3f-4729-acff-7d8b363f4aa2.png)

**Comment by camenduru** [comment]
pip install torch==2.0.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

**Comment by camenduru** [comment]
!sed -i -e 's/torch/torch==2.0.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118/g' requirements_versions.txt

**Comment by camenduru** [comment]
`!pip install -q torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1+cu118 torchtext==0.15.1 torchdata==0.6.0 --extra-index-url https://download.pytorch.org/whl/cu118 -U`

**Comment by camenduru** [comment]
![image](https://user-images.githubusercontent.com/54370274/229601539-214a1ad7-cc79-432b-8755-7ccd0eed2bdb.png)

**Comment by camenduru** [comment]
!pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 torchtext==0.14.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu116 -U

**Comment by etherealxx** [comment]
camen, seems cagliestro (linaqruf's) colab already had the fix. Might worth checking for references.

**Comment by camenduru** [comment]
I am just cleaning I fixed it

**Comment by camenduru** [comment]
![image](https://user-images.githubusercontent.com/54370274/229603485-391ff6eb-a5b2-4a3f-b57b-21e7624c1c54.png)
