### ISSUE TITLE
[Bug]: Can not use 'R-ESRGAN 4x+ Anime6B' for upscale in Extras

### ISSUE THREAD

**Issue by IPv6** [camenduru/stable-diffusion-webui-colab#345]
### What happened?

Can not use 'R-ESRGAN 4x+ Anime6B' for upscale in Extras

### Console logs

```shell
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=2048x2048 at 0x7F1D84A752E0>, None, '', '', True, 0, 2, 512, 512, True, 'R-ESRGAN 4x+ Anime6B', 'None', 0, 0, 0, 0, 'None', False, False, 240, 10, 10) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/postprocessing.py", line 70, in run_postprocessing
    images.save_image(pp.image, path=outpath, basename=basename, seed=None, prompt=None, extension=opts.samples_format, info=infotext, short_filename=True, no_prompt=True, grid=False, pnginfo_section_name="extras", existing_info=existing_pnginfo, forced_filename=None)
  File "/content/stable-diffusion-webui/modules/images.py", line 584, in save_image
    _atomically_save_image(image, fullfn_without_extension, extension)
  File "/content/stable-diffusion-webui/modules/images.py", line 554, in _atomically_save_image
    image_to_save.save(temp_file_path, format=image_format, quality=opts.jpeg_quality, pnginfo=pnginfo_data)
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 2431, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.9/dist-packages/PIL/PngImagePlugin.py", line 1331, in _save
    data = name + b"\0\0" + zlib.compress(icc)
TypeError: a bytes-like object is required, not 'str'
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/nightly/stable_diffusion_inpainting_webui_colab.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by camenduru** [comment]
Hi @IPv6 I am unable to regenerate. Could you please provide me with all the upscale configs?

![image](https://user-images.githubusercontent.com/54370274/230518006-58968e60-fe2c-4ce2-9ebd-c695d2037648.png)

**Comment by IPv6** [comment]
Hello @camenduru - tried with fresh colab and reproduced it again

Colab: https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/nightly/anything_3_webui_colab.ipynb
Full logs: [logs.txt](https://github.com/camenduru/stable-diffusion-webui-colab/files/11178537/logs.txt)

Error: 
```
	Tile 120/121
	Tile 121/121
Error executing callback before_image_saved_callback for /content/stable-diffusion-webui/extensions/sd_webui_stealth_pnginfo/scripts/stealth_pnginfo.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/script_callbacks.py", line 151, in before_image_saved_callback
    c.callback(params)
  File "/content/stable-diffusion-webui/extensions/sd_webui_stealth_pnginfo/scripts/stealth_pnginfo.py", line 20, in add_stealth_pnginfo
    str_parameters = params.pnginfo['parameters']
KeyError: 'parameters'

Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=2048x2048 at 0x7FE0ED71BA60>, None, '', '', True, 0, 4, 512, 512, True, 'R-ESRGAN 4x+ Anime6B', 'None', 0, 0, 0, 0, 'None', False, False, 240, 10, 10) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/postprocessing.py", line 70, in run_postprocessing
    images.save_image(pp.image, path=outpath, basename=basename, seed=None, prompt=None, extension=opts.samples_format, info=infotext, short_filename=True, no_prompt=True, grid=False, pnginfo_section_name="extras", existing_info=existing_pnginfo, forced_filename=None)
  File "/content/stable-diffusion-webui/modules/images.py", line 584, in save_image
    _atomically_save_image(image, fullfn_without_extension, extension)
  File "/content/stable-diffusion-webui/modules/images.py", line 554, in _atomically_save_image
    image_to_save.save(temp_file_path, format=image_format, quality=opts.jpeg_quality, pnginfo=pnginfo_data)
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 2431, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.9/dist-packages/PIL/PngImagePlugin.py", line 1331, in _save
    data = name + b"\0\0" + zlib.compress(icc)
TypeError: a bytes-like object is required, not 'str'
```

Screenshot: 
<img width="2048" alt="Screenshot 2023-04-07 at 14 30 01" src="https://user-images.githubusercontent.com/40495/230601952-a0b7f7e2-0e41-4687-886b-62d5e4d0859f.png">

Image used:
![00000](https://user-images.githubusercontent.com/40495/230601985-bc7f1b7b-5829-48d3-a5fb-fc54e6ccaf9f.png)

**Comment by camenduru** [comment]
Hi @IPv6 looks like `sd_webui_stealth_pnginfo` extension has bug add # before 
```
!git clone https://github.com/camenduru/sd_webui_stealth_pnginfo /content/stable-diffusion-webui/extensions/sd_webui_stealth_pnginfo
```

![image](https://user-images.githubusercontent.com/54370274/230673032-239adcd9-538b-46a9-99bf-f48c10e5f352.png)

**Comment by camenduru** [comment]
![image](https://user-images.githubusercontent.com/54370274/230682240-01fdf00a-65e7-43e2-8f4d-a9e6f0779248.png)
![image](https://user-images.githubusercontent.com/54370274/230682474-8b3f6f97-1fbd-4572-91b7-4e0fa95f5115.png)

looks like we have a bug in `extensions/sd_webui_stealth_pnginfo`

if you save the image without `icc_profile` it is working just save the image without png info then use upscale

```
parameters

None


icc_profile

b'\x00\x00\x02Tlcms\x040\x00\x00mntrRGB XYZ \x07\xe7\x00\x04\x00\x06\x00\x0b\x00\x1d\x00+acspAPPL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf6\xd6\x00\x01\x00\x00\x00\x00\xd3-lcms\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0bdesc\x00\x00\x01\x08\x00\x00\x00>cprt\x00\x00\x01H\x00\x00\x00Lwtpt\x00\x00\x01\x94\x00\x00\x00\x14chad\x00\x00\x01\xa8\x00\x00\x00,rXYZ\x00\x00\x01\xd4\x00\x00\x00\x14bXYZ\x00\x00\x01\xe8\x00\x00\x00\x14gXYZ\x00\x00\x01\xfc\x00\x00\x00\x14rTRC\x00\x00\x02\x10\x00\x00\x00 gTRC\x00\x00\x02\x10\x00\x00\x00 bTRC\x00\x00\x02\x10\x00\x00\x00 chrm\x00\x00\x020\x00\x00\x00$mluc\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x0cenUS\x00\x00\x00"\x00\x00\x00\x1c\x00s\x00R\x00G\x00B\x00 \x00I\x00E\x00C\x006\x001\x009\x006\x006\x00-\x002\x00.\x001\x00\x00mluc\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x0cenUS\x00\x00\x000\x00\x00\x00\x1c\x00N\x00o\x00 \x00c\x00o\x00p\x00y\x00r\x00i\x00g\x00h\x00t\x00,\x00 \x00u\x00s\x00e\x00 \x00f\x00r\x00e\x00e\x00l\x00yXYZ \x00\x00\x00\x00\x00\x00\xf6\xd6\x00\x01\x00\x00\x00\x00\xd3-sf32\x00\x00\x00\x00\x00\x01\x0cB\x00\x00\x05\xde\xff\xff\xf3%\x00\x00\x07\x93\x00\x00\xfd\x90\xff\xff\xfb\xa1\xff\xff\xfd\xa2\x00\x00\x03\xdc\x00\x00\xc0nXYZ \x00\x00\x00\x00\x00\x00o\xa0\x00\x008\xf5\x00\x00\x03\x90XYZ \x00\x00\x00\x00\x00\x00$\x9f\x00\x00\x0f\x84\x00\x00\xb6\xc3XYZ \x00\x00\x00\x00\x00\x00b\x97\x00\x00\xb7\x87\x00\x00\x18\xd9para\x00\x00\x00\x00\x00\x03\x00\x00\x00\x02ff\x00\x00\xf2\xa7\x00\x00\rY\x00\x00\x13\xd0\x00\x00\n[chrm\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\xa3\xd7\x00\x00T{\x00\x00L\xcd\x00\x00\x99\x9a\x00\x00&f\x00\x00\x0f\\'


XML:com.adobe.xmp

<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.5.0">
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about=""
xmlns:xmp="http://ns.adobe.com/xap/1.0/"
xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
xmlns:exif="http://ns.adobe.com/exif/1.0/"
xmlns:tiff="http://ns.adobe.com/tiff/1.0/"
xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
xmp:CreateDate="2023-04-06T18:38:11+0300"
xmp:ModifyDate="2023-04-06T18:46:58+03:00"
xmp:MetadataDate="2023-04-06T18:46:58+03:00"
photoshop:DateCreated="2023-04-06T18:38:11+0300"
photoshop:ColorMode="3"
photoshop:ICCProfile="sRGB IEC61966-2.1"
exif:PixelXDimension="512"
exif:PixelYDimension="512"
exif:ColorSpace="1"
tiff:ImageWidth="512"
tiff:ImageLength="512"
tiff:ResolutionUnit="2"
tiff:XResolution="96/1"
tiff:YResolution="96/1">
<xmpMM:History>
<rdf:Seq>
<rdf:li
stEvt:action="produced"
stEvt:softwareAgent="Affinity Photo 2 Beta 2.1.0"
stEvt:when="2023-04-06T18:46:58+03:00"/>
</rdf:Seq>
</xmpMM:History>
</rdf:Description>
</rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>


dpi

(96.012, 96.012)


postprocessing

Postprocess upscale by: 4, Postprocess upscaler: 4x-UltraSharp


extras

Postprocess upscale by: 4, Postprocess upscaler: 4x-UltraSharp
```
