### ISSUE TITLE
[Bug]: OSError - undefined symbol

### ISSUE THREAD

**Issue by ClownOfMadness** [camenduru/stable-diffusion-webui-colab#350]
### What happened?

![image](https://user-images.githubusercontent.com/52707645/230712755-99787866-f5be-402d-9c79-d67e34c02f16.png)

After a while decided to go back to use this colab and now it throws me this error
note: this is a duplicate of a stable version of the Meina_V8 model colab, it has few extensions added but i removed them, restarted and the issue remains

### Colab cell output

```shell
2023-04-08 08:48:27.968996: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-08 08:48:30.289860: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 362, in <module>
    start()
  File "/content/stable-diffusion-webui/launch.py", line 352, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "/content/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 7, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/imports.py", line 153, in <module>
    _TORCHTEXT_LEGACY: bool = _TORCHTEXT_AVAILABLE and _compare_version("torchtext", operator.lt, "0.11.0")
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/imports.py", line 71, in _compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/dist-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/usr/local/lib/python3.9/dist-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/usr/local/lib/python3.9/dist-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.9/dist-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorElN3c106SymIntE
```

### Which colab and model(s) were you using when the error occurred?

https://civitai.com/models/7240/meinamix

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by MuLoo** [comment]
same error, please help

**Comment by MuLoo** [comment]
> same error, please help

re-run `install.ipynb` works for me

**Comment by camenduru** [comment]
Hi @ClownOfMadness 👋, please check out MuLoo's answer

**Comment by ClownOfMadness** [comment]
> Hi @ClownOfMadness 👋, please check out MuLoo's answer

by that you mean add this line at the end? or run it after i get an error?

**Comment by camenduru** [comment]
please run `One Time Install & Update` and if you are using copy please update your code
![image](https://user-images.githubusercontent.com/54370274/230719686-2853c652-e44c-4aea-99c4-3e68a551d0fe.png)

**Comment by ClownOfMadness** [comment]
oh no, i am using it without google drive, but it does seem that the code i am using is outdated as i tried running any of the latest stable version and no issue. thank you!
