### ISSUE TITLE
[Bug] CN1.1: models names mismatch

### ISSUE THREAD

**Issue by IPv6** [camenduru/stable-diffusion-webui-colab#364]
Trying to use ControlNet 1.1 from nighly colab but getting the error

```
Startup time: 95.1s (import torch: 8.1s, import gradio: 1.3s, import ldm: 2.3s, other imports: 2.3s, setup codeformer: 0.2s, load scripts: 42.2s, load SD checkpoint: 30.5s, create ui: 7.1s, gradio launch: 0.9s).
Loading model: control_v11p_sd15_normalbae_fp16 [592a19d8]
Loaded state_dict from [/content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_normalbae_fp16.safetensors]
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 719, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 502, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 544, in build_control_model
    assert os.path.exists(override_config), f'Error: The model config {override_config} is missing. ControlNet 1.1 must have configs.'
AssertionError: Error: The model config /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_normalbae_fp16.yaml is missing. ControlNet 1.1 must have configs.
```

But the content of extension models HAVE the corresponding file - but it is named control_v11p_sd15_normalbae.yaml (no _fp16 postfix). Seems model downloading should omit this postfix (extension inherit yaml name from model file name)

**Comment by camenduru** [comment]
Hi @IPv6 👋 maybe fixed please try again
