### ISSUE TITLE
[Bug]: Your local changes to the following files would be overwritten by checkout

### ISSUE THREAD

**Issue by chuanSir123** [camenduru/stable-diffusion-webui-colab#365]
### What happened?

excuse me,When I use colab to mount and start, there is an error that causes the startup to fail.

### Colab cell output

```shell
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: 5b3af030dd83e0297272d861c19477735d0317ec...
Traceback (most recent call last):
  File "/content/drive/MyDrive/share/0417001/stable-diffusion-webui/launch.py", line 380, in <module>
    prepare_environment()
  File "/content/drive/MyDrive/share/0417001/stable-diffusion-webui/launch.py", line 317, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "/content/drive/MyDrive/share/0417001/stable-diffusion-webui/launch.py", line 164, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "/content/drive/MyDrive/share/0417001/stable-diffusion-webui/launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit 5b3af030dd83e0297272d861c19477735d0317ec for K-diffusion.
Command: "git" -C "/content/drive/MyDrive/share/0417001/stable-diffusion-webui/repositories/k-diffusion" checkout 5b3af030dd83e0297272d861c19477735d0317ec
Error code: 1
stdout: <empty>
stderr: error: Your local changes to the following files would be overwritten by checkout:
	train.py
Please commit your changes or stash them before you switch branches.
Aborting
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/stable_diffusion_1_5_webui_colab.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by chuanSir123** [comment]
sorry，When I use Google Drive to mount the startup, there is an error that causes the startup to fail

**Comment by chuanSir123** [comment]
> 
Tried everything you said, still doesn't work. Finally, I directly removed this line of error reporting code, and now it is running. What is the impact of deleting this line?
