### ISSUE TITLE
[Bug]: ControlNet model not found

### ISSUE THREAD

**Issue by mingjing33** [camenduru/stable-diffusion-webui-colab#369]
### What happened?

While using Drive Branch with ControlNet , launching successfully

When start Generating Txt2Image, Following error will occur. Already Update Installation the latest release

### Colab cell output

```shell
/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 795, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 514, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 529, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/drive/run.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

### If you used HiRes mode when the error occurred, please provide the Hires info

Hires steps: 20, Hires upscale: 3, Variation seed: 1182048904, ControlNet Model: None, ControlNet Module: none, ControlNet Weight: 2, ControlNet Enabled: True, Denoising strength: 0.3, ControlNet Guidance End: 1, Variation seed strength: 0.7, ControlNet Guidance Start: 0

**Comment by Anonimouche** [comment]
You're trying to use controlnet without using any model, that's your issue

**Comment by camenduru** [comment]
Hi @mingjing33 👋please try again
