### ISSUE TITLE
use img2img batch Error

### ISSUE THREAD

**Issue by muuua1004** [camenduru/stable-diffusion-webui-colab#387]
### What happened?

when I use img2img batch, created a new folder 'input' under '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/'
but when generate ,prompt error

### Colab cell output

```shell
Error completing request
Arguments: ('task(jt9efb3l9r31lg6)', 5, '(HD Photo), Ultra-detailed Photo, RAW Photo, ((intricate)), cinematic lighting, (((perfect face, beautiful detailed face))), anatomical, flawless, clean,\n(((cheerful expression))), (cowboy shot:1.2), (((standing))), \n((1 queen)), ((absurdly long hair)), very long hair, ((tight dress)), tight turtleneck backless dress, turtleneck dress, backless dresses, (Knit Dress), (white dress:1.4), (openwork dress:1.4), (white skin:1.3), \n((blurred background)), (street background), (big firm breasts:1.2), (pronounced feminine feature:1.2), (perfect female body:1.2), (((cleavage))),  ', 'illustration, 3d, sepia, painting, cartoons, sketch, (worst quality:1.5), (low quality:1.5), (normal quality:1.5), lowres, bad anatomy, bad hands,  (mole:1.5), ((monochrome)), (grayscale:1.2), futanari, full-package_futanari, penis_from_girl, newhalf, collapsed eyeshadow, multiple eyebrows, vaginas in breasts,holes on breasts, fleckles, stretched nipples, gigantic penis, nipples on buttocks, analog, analogphoto, signatre, logo,2 faces, (worst quality, low quality:1.3), simple background, (((logo, watermark, text))), (bad-hands-5:1.5)', [], <PIL.Image.Image image mode=RGBA size=960x536 at 0x7F6C8897D130>, None, None, None, None, None, None, 150, 15, 4, 0, 1, False, False, 3, 1, 13, 1.5, 0.51, -1.0, -1.0, 0, 0, 0, False, 1080, 1920, 0, 0, 32, 0, '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/intput/', '', '', [], 0, '\n    <div style="padding: 10px">\n      <div>Estimated VRAM usage: <span style="color: rgb(0.48, 248.73, 123.03)">4543.00 MB / 15102 MB (30.08%)</span></div>\n      <div>(4137 MB system + 369.09 MB used)</div>\n    </div>\n    ', False, '', 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <controlnet.py.UiControlNetUnit object at 0x7f6cc99cb280>, <controlnet.py.UiControlNetUnit object at 0x7f6cca9c8430>, <controlnet.py.UiControlNetUnit object at 0x7f6ccb072370>, <controlnet.py.UiControlNetUnit object at 0x7f6cc9d33ac0>, False, False, 'Denoised', 2.0, 0.0, 0.0, 'Make a video file', 'mp4', 'h264', 30.0, 0.0, 0.0, False, 5.0, True, True, False, False, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/img2img.py", line 165, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 25, in img2img_process_batch_hijack
    return getattr(img2img, '__controlnet_original_process_batch')(p, *args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/img2img.py", line 23, in process_batch
    images = shared.listfiles(input_dir)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/shared.py", line 729, in listfiles
    filenames = [os.path.join(dirname, x) for x in sorted(os.listdir(dirname)) if not x.startswith(".")]
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/intput/'
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/drive/run.ipynb#scrollTo=SaAJk33ppFw1

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by muuua1004** [comment]
I found a solution, that is, click on the relevant path on the colab interface, and then copy that path, that's it.
