### ISSUE TITLE
abyss orange mix doesnt work

### ISSUE THREAD

**Issue by soliwoli** [camenduru/stable-diffusion-webui-colab#39]
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /__w/safetensors/safetensors/safetensors/src/tensor.rs:117:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "launch.py", line 295, in <module>
    start()
  File "launch.py", line 290, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 133, in webui
    initialize()
  File "/content/stable-diffusion-webui/webui.py", line 63, in initialize
    modules.sd_models.load_model()
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 313, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 196, in load_model_weights
    sd = read_state_dict(checkpoint_file)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 171, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=map_location or shared.weight_load_location)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 98, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 0

**Comment by soliwoli** [comment]
ty :)

**Comment by soliwoli** [comment]
> How was this fixed? getting a similar error while loading a checkpoint in huggingface. Checkpoint works in colab if I upload to drive but not if I link huggingface model?

its something wrong with your juypter notebook, try looking in commits on jan 13
