### ISSUE TITLE
[Bug]: remote.moe

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#409]
### What happened?

remote.moe

### Colab cell output

```shell
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
all detected, remote.moe trying to connect...
Warning: Permanently added 'localhost.run,35.171.254.69' (RSA) to the list of known hosts.
Error loading script: ssh_tunnel.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/sd-webui-tunnels/scripts/ssh_tunnel.py", line 138, in <module>
    ssh_tunnel(REMOTE_MOE)
  File "/content/stable-diffusion-webui/extensions/sd-webui-tunnels/scripts/ssh_tunnel.py", line 114, in ssh_tunnel
    raise RuntimeError(f"Failed to run {host}")
RuntimeError: Failed to run remote.moe
```

### Which colab and model(s) were you using when the error occurred?

all

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by victorbarlac** [comment]
I was about to report that

**Comment by FlickerMi** [comment]
me too

**Comment by camenduru** [comment]
https://github.com/fasmide/remotemoe/issues/21
