### ISSUE TITLE
[Bug]: Reference-based-SD-CN-Animation

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#410]
### What happened?

Reference-based-SD-CN-Animation

### Colab cell output

```shell
Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple --disable-safe-unpickle
2023-05-07 02:13:30.477975: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Error loading script: base_ui.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/Reference-based-SD-CN-Animation/scripts/base_ui.py", line 30, in <module>
    from vid2vid import *
ModuleNotFoundError: No module named 'vid2vid'

Error loading script: vid2vid.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/Reference-based-SD-CN-Animation/scripts/vid2vid.py", line 42, in <module>
    from flow_utils import RAFT_estimate_flow, RAFT_clear_memory, compute_diff_map
ModuleNotFoundError: No module named 'flow_utils'
```

### Which colab and model(s) were you using when the error occurred?

video

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by seq2193** [comment]
Hello! Can you  Add EasyNegativeV2 ? thank you!

**Comment by camenduru** [comment]
Hi @seq2193 👋 thanks for the suggestion ❤ added
