### ISSUE TITLE
[Error]: a little problem

### ISSUE THREAD

**Issue by muuua1004** [camenduru/stable-diffusion-webui-colab#411]
### What happened?

sometime after 1 picture finished, an error will appear, and I had to start SD with 'run' again. the connection between webui and google drive still goes well, like I still can change check point, and still can run 'generate', the progress still can go step by step, just when the picture finished, no file created in 'output' folder, and it seems have no solution to solve this problem by not disconnect and reboot again. 
I wounder if there is some way to solve this problem by not disconnect and reboot again. 
This problem always appeared some time after startup, but the time is not same, maybe 1 hour later, maybe 3hour later.

### Colab cell output

```shell
79% 27/34 [01:39<00:25,  3.68s/it]
 82% 28/34 [01:42<00:22,  3.69s/it]
 85% 29/34 [01:46<00:18,  3.70s/it]
 88% 30/34 [01:50<00:14,  3.70s/it]
 91% 31/34 [01:54<00:11,  3.69s/it]
 94% 32/34 [01:57<00:07,  3.69s/it]
 97% 33/34 [02:01<00:03,  3.68s/it]
100% 34/34 [02:05<00:00,  3.68s/it]
Error completing request
Arguments: ('task(ni03qz9sgkwbphy)', 0, '((Ultra-HD Photo)), Ultra-detailed RAW color Photo,  (intricate), cinematic lighting, (perfect face, beautiful detailed face), anatomical, flawless, clean, (((enjoyment expression))),  \n1 queen, standing, white hair, long hair, (((wearing Armed Chest Mecha Armor))), (((red Metal Mecha Armor, luxurious Mecha Armor, Large-pattern-openwork Mecha Armor))), lace-trimmed legwear, Crop Top, \npronounced feminine feature, perfect female body, cleavage,', 'illustration, 3d, sepia, painting, cartoons, sketch, (worst quality:1.5), (low quality:1.5), (normal quality:1.5), lowres, bad anatomy, bad hands,  (mole:1.5), ((monochrome)), (grayscale:1.2), futanari, full-package_futanari, penis_from_girl, newhalf, collapsed eyeshadow, multiple eyebrows, vaginas in breasts,holes on breasts, fleckles, stretched nipples, gigantic penis, nipples on buttocks, analog, analogphoto, signatre, logo,2 faces, simple background, (((logo, watermark, text))), (bad-hands-5:1.5)', [], <PIL.Image.Image image mode=RGBA size=1920x1080 at 0x7F9D666DBBB0>, None, None, None, None, None, None, 54, 15, 4, 0, 1, True, False, 3, 1, 12, 1.5, 0.62, -1.0, -1.0, 0, 0, 0, False, 1080, 1920, 0, 0, 32, 0, '', '', '', [], 0, '\n    <div style="padding: 10px">\n      <div>Estimated VRAM usage: <span style="color: rgb(0.64, 249.64, 107.25)">4679.00 MB / 15102 MB (30.98%)</span></div>\n      <div>(4273 MB system + 369.09 MB used)</div>\n    </div>\n    ', False, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, False, True, True, False, 2048, 128, False, '', 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <controlnet.py.UiControlNetUnit object at 0x7f9d68402050>, <controlnet.py.UiControlNetUnit object at 0x7f9d684031c0>, <controlnet.py.UiControlNetUnit object at 0x7f9d67386980>, <controlnet.py.UiControlNetUnit object at 0x7f9d6882acb0>, False, False, 'Denoised', 2.0, 0.0, 0.0, 'Make a video file', 'mp4', 'h264', 30.0, 0.0, 0.0, False, 5.0, True, True, False, False, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/img2img.py", line 171, in img2img
    processed = process_images(p)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/processing.py", line 684, in process_images_inner
    images.save_image(image, p.outpath_samples, "", seeds[i], prompts[i], opts.samples_format, info=infotext(n, i), p=p)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/images.py", line 499, in save_image
    os.makedirs(path, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 107] Transport endpoint is not connected: 'outputs'
```

### Which colab and model(s) were you using when the error occurred?

https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

**Comment by haik74** [comment]
I have problem with DEFORUM, stop working on google colab
