### ISSUE TITLE
Controlnet 1.1 issues

### ISSUE THREAD

**Issue by JerryOver** [camenduru/stable-diffusion-webui-colab#418]
### What happened?

I have told Mikubill in the past about controlnet not always working like you said, but they never resolved that issue for me over there. I have used controlnet in the past with zero issue but that was at the beginning. When I try to use it now, it works only some of the time and then it acts like I don't have controlnet enabled. Forgive me, but do you think with their newer controlnet that your webui's has a version of python that's not very compatible with their more recent version of controlnet?

### Colab cell output

```shell
It will also sometimes act as though there is no controlnet models:

Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1017, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 689, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 703, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None
```

### Which colab and model(s) were you using when the error occurred?

stable version of https://civitai.com/models/8030/analog-madness-realistic-model

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

**Comment by JerryOver** [comment]
I think you fixed it. I was using the Nightly version of GhostMix, and it works as long as I go ahead and set what I want to do in controlnet when the browser loads the WEBUI. If the browser stops responding to a change that I make later on in controlnet then I will just reload the browser and set everything back up. It'll work after that. It's not perfect, but it works. I am content with it the way it is. I rather have it working than not.
