### ISSUE TITLE
[Bug]: can't load Lora in this version

### ISSUE THREAD

**Issue by harry-liao** [camenduru/stable-diffusion-webui-colab#428]
### What happened?

I updated the newest version yesterday. I can generate image properly but can't load Lora w prompt anymore. 
I have restart the colab and still got this problem : ( . 
attach colab output below: 

### Colab cell output

```shell
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 273.7s (import gradio: 2.6s, import ldm: 6.7s, other imports: 8.5s, list extensions: 64.9s, list SD models: 0.4s, setup codeformer: 9.5s, load scripts: 68.8s, load SD checkpoint: 91.6s, create ui: 20.6s, gradio launch: 0.1s).
locon load lora method
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7f623a7c6f20>]: AttributeError
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 170, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/a1111-sd-webui-locon/scripts/main.py", line 371, in load_lora
    lora.mtime = os.path.getmtime(lora_on_disk.filename)
AttributeError: 'str' object has no attribute 'filename'

Error running process_batch: /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 427, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 190, in process_batch
    if not args[0]:
IndexError: tuple index out of range
```

### Which colab and model(s) were you using when the error occurred?

https://github.com/camenduru/stable-diffusion-webui-colab.git
https://civitai.com/models/70088?modelVersionId=74751

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by Wlison1** [comment]
Yes, I also encountered the same problem. This problem has been bothering me for two days

**Comment by camenduru** [comment]
Hi @harry-liao 👋 thanks for the info ❤ please try again

**Comment by Susan0025** [comment]
Did you solve it? I still got the same problem.

**Comment by harry-liao** [comment]
@camenduru Thanks!!! I can load Lora now.
@Susan0025 It work for me
