### ISSUE TITLE
[Bug]: Error loading script: infinite-zoom.py

### ISSUE THREAD

**Issue by ChangQing666** [camenduru/stable-diffusion-webui-colab#432]
### What happened?

when I installed the infinite-zoom from extentions, and restart the run.ipynb, the error shows bellows

### Colab cell output

```shell
Error loading script: infinite-zoom.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py", line 2, in <module>
    from iz_helpers.ui import on_ui_tabs
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/iz_helpers/ui.py", line 2, in <module>
    from .run import create_zoom
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/iz_helpers/run.py", line 6, in <module>
    from modules.paths_internal import script_path
ModuleNotFoundError: No module named 'modules.paths_internal'
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/drive/run.ipynb

https://github.com/v8hid/infinite-zoom-automatic1111-webui.git

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

**Comment by camenduru** [comment]
hi @ChangQing666 👋 thanks for the info ❤ please try again

**Comment by camenduru** [comment]
please use `One Time Install & Update` colab

**Comment by ChangQing666** [comment]
> 
Perfect operation after update，thank u
