### ISSUE TITLE
[Bug]: Loading sd-webui-additional-networks error

### ISSUE THREAD

**Issue by Githb-alexsherman** [camenduru/stable-diffusion-webui-colab#433]
### What happened?

When I load the latest run.ipynb file, sd-webui-additional-networks will report an error, which makes it unable to use normally after entering the WebUI，please fix it

### Colab cell output

```shell
Create LRU cache (max_size=16) for preprocessor results.
Error calling: /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py/ui
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'

Create LRU cache (max_size=16) for preprocessor results.
Error calling: /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py/ui
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'

*Deforum ControlNet support: enabled*
Error executing callback ui_tabs_callback for /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 290, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/metadata_editor.py", line 462, in setup_ui
    outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]],
IndexError: list index out of range
```

### Which colab and model(s) were you using when the error occurred?

nothing

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

**Comment by stephonye** [comment]
I had the same problem.

**Comment by camenduru** [comment]
please use `One Time Install & Update` colab
