### ISSUE TITLE
[Bug]: Failed to generate an image and displayed "AssertionError: could not find upscaler named SwinIR_4x"

### ISSUE THREAD

**Issue by mnrr01** [camenduru/stable-diffusion-webui-colab#442]
### What happened?

"AssertionError: could not find upscaler named SwinIR_4x" was displayed when using model deliberate_v2 to generate images failed

### Colab cell output

```shell
Total progress: 0it [00:00, ?it/s]Error completing request
Arguments: ('task(lr12fuphifbbrmg)', "(Masterpiece, 4K resolution, ultra-realistic, very detailed:1.3), tall and curvy woman with loose ponytail framing her face, wearing a fully ripped open white Spider-Man costume revealing her plump and round breasts:1.2, shiny smooth skin with small freckles and sweat droplets that shows pores, detailed face with deep ((blue eyes:1.2)) and (rosy lips:1.1) that look inviting. Her body features a thin (waist:1.1), wide and rounded hips, thick legs and round buttocks:1.1. She stands confidently on the side of a building, hanging from a web, looking directly at the viewer, daring them to resist her charms. The surrounding environment is a sandy urban cityscape that is dimly lit by dynamic lights and a full moon.\nIn the background, there's a girl on top of town, beautiful shaded face, wearing the same Spider-Man costume as the protagonist, she's another superheroine who looks charismatic. She is shown in a spider-man pose with a show of strength, jumping from one building to another. The sandy urban environment shows rough texture and has a photorealistic feel (0.8). It contains sparks and sunlight that make it vibrant and colorful.\nThe entire image is shot using a DSLR camera with natural lighting and subsurface scattering. It has a film grain effect, which gives it a raw photo feel. The image quality is at high-resolution UHD (8k), making it sharp and clear. The composition is symmetrical, with the main focus being on the protagonist. The image has won multiple awards for its hyper-detailed and vivid depiction of White Spider-Woman in action.\nOverall, the painting portrays a seductive and confident female superheroine with exquisite physical features, hanging on the side of a building, ready to save the city from any danger that might arise.", 'mask, bad-hands-5, badhandv4, easynegative, By bad artist, monotone, low quality, close up, cropped, greyscale, watermark, hands, finger, cleavage, child', [], 50, 13, True, False, 1, 1, 6, 2829510615.0, -1.0, 0, 0, 0, False, 768, 512, True, 0.3, 2, 'SwinIR_4x', 0, 0, 0, [], 0, False, '', 0, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fd5390764a0>, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, False, False, 'positive', 'comma', 0, False, False, '', '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, False, 50) {}
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/processing.py", line 866, in sample
    assert len([x for x in shared.sd_upscalers if x.name == self.hr_upscaler]) > 0, f"could not find upscaler named {self.hr_upscaler}"
AssertionError: could not find upscaler named SwinIR_4x
```

### Which colab and model(s) were you using when the error occurred?

https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive
model ：deliberate_v2

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

**Comment by ShinChven** [comment]
Please try selecting the upscaler manually after loading configurations.

**Comment by camenduru** [comment]
maybe fixed please try again

**Comment by ShinChven** [comment]
Based on my experience, the upscaler name consistently changes from `SwinIR_4x` to `SwinIR 4x` every time I start the sdwebui. 
This issue occurs in both the original version and this Colab versions.
