### ISSUE TITLE
new version still broken 

### ISSUE THREAD

**Issue by megazaz80** [camenduru/stable-diffusion-webui-colab#45]
https://github.com/camenduru/stable-diffusion-webui-colab/issues/35#issuecomment-1376905439

**Comment by megazaz80** [comment]
Generated images are worse quality, people are deformed, crippled, with extra limbs even if putting negative promts...

**Comment by 96312** [comment]
Can confirm, the error I keep getting is this -

```
Traceback (most recent call last):  
File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f  
    res = list(func(*args, **kwargs))  
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f  
    res = func(*args, **kwargs)  
  File "/content/stable-diffusion-webui/modules/img2img.py", line 148, in img2img  
    processed = process_images(p)  
  File "/content/stable-diffusion-webui/modules/processing.py", line 479, in process_images  
    res = process_images_inner(p)  
  File "/content/stable-diffusion-webui/modules/processing.py", line 572, in process_images_inner  
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)  
  File "/content/stable-diffusion-webui/modules/processing.py", line 941, in init  
    image_masked.paste(image.convert("RGBA").convert("RGBa"), mask=ImageOps.invert(self.mask_for_overlay.convert('L')))  
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 1731, in paste  
    self.im.paste(im, box, mask.im)  
ValueError: images do not match
```

**Comment by SkyFryz24** [comment]
How do we turn back to v1.6?

**Comment by camenduru** [comment]
go back to the old version
`!git clone https://github.com/camenduru/stable-diffusion-webui`
to this 
`!git clone -b v1.6 https://github.com/camenduru/stable-diffusion-webui`

**Comment by SkyFryz24** [comment]
> go back to the old version `!git clone https://github.com/camenduru/stable-diffusion-webui` to this `!git clone -b v1.6 https://github.com/camenduru/stable-diffusion-webui`

Thank you!!
