### ISSUE TITLE
[Bug]: error when running sd-webui into Google Drive colab script

### ISSUE THREAD

**Issue by aspieteer** [camenduru/stable-diffusion-webui-colab#450]
### What happened?

Running the "Install" script , the error code about CodeFormer popup when curser on the last line of launch.py . 

### Colab cell output

```shell
Python 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
Version: <none>
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/taming-transformers...
Cloning K-diffusion into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/k-diffusion...
Cloning CodeFormer into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/CodeFormer...
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 40, in <module>
    main()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 30, in main
    prepare_environment()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/launch_utils.py", line 291, in prepare_environment
    git_clone(codeformer_repo, repo_dir('CodeFormer'), "CodeFormer", codeformer_commit_hash)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/launch_utils.py", line 150, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', None, "Couldn't checkout {name}'s hash: {commithash}")
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't checkout {name}'s hash: {commithash}.
Command: "git" -C "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/CodeFormer" checkout c5b4593074ba6214284d6acd5f1719b6c5d739af
Error code: 1
stderr: error: Your local changes to the following files would be overwritten by checkout:
	basicsr/data/ffhq_blind_dataset.py
	basicsr/data/ffhq_blind_joint_dataset.py
	basicsr/data/gaussian_kernels.py
	options/CodeFormer_colorization.yml
	options/CodeFormer_inpainting.yml
	options/CodeFormer_stage2.yml
	options/CodeFormer_stage3.yml
	options/VQGAN_512_ds32_nearest_stage1.yml
	scripts/crop_align_face.py
Please commit your changes or stash them before you switch branches.
```

### Which colab and model(s) were you using when the error occurred?

https://github.com/camenduru/stable-diffusion-webui-colab/blob/drive/install.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by camenduru** [comment]
maybe fixed please try again
