### ISSUE TITLE
cannot save images with elysium_anime_2 (or is it just me?)

### ISSUE THREAD

**Issue by KiritoMania** [camenduru/stable-diffusion-webui-colab#46]
when i try to save an image, it won't save and found this error in the colab:
Error completing request
Arguments: ('', [], False, -1) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/ui.py", line 113, in save_files
    data = json.loads(js_data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by etherealxx** [comment]
can you right click then save? or right click on the colab file explorer then save?

**Comment by camenduru** [comment]
Hi @KiritoMania  👋 we back to v1.6 please try again
