### ISSUE TITLE
[Bug]: lora can't be loaded.

### ISSUE THREAD

**Issue by he3764** [camenduru/stable-diffusion-webui-colab#462]
### What happened?

Running the latest run, lora can't be loaded.

### Colab cell output

```shell
all detected, cloudflared trying to connect...
Error loading script: lora_script.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions-builtin/Lora/scripts/lora_script.py", line 7, in <module>
    import lora
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 362, in <module>
    list_available_loras()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 343, in list_available_loras
    os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/content/fused-lora'
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/drive/run.ipynb

**Comment by Vsevolod-Shustov** [comment]
You have remote.moe working? Hasn't been working for me for months.

**Comment by he3764** [comment]
> You have remote.moe working? Hasn't been working for me for months.

no work, I forgot to change the default option for feedback.

**Comment by camenduru** [comment]
maybe fixed please try again
