### ISSUE TITLE
[Bug]: Can not load Roop extention on stable_diffusion_inpainting_webui_colab

### ISSUE THREAD

**Issue by wsjhear1984** [camenduru/stable-diffusion-webui-colab#473]
### What happened?

I ran stable_diffusion_inpainting_webui_colab on google colab and installed roop from the extention tab. However, when I tried reload the web ui to take effect the extention installation, the extention can not be loaded.
Can you please help take a look? Thank you.

### Colab cell output

```shell
Restarting UI...
Closing server running on port: 7860
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
2023-08-30 10:18:38,936 - ControlNet - INFO - ControlNet v1.1.313
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-roop/scripts/api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "/content/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "/content/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-roop/scripts/cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "/content/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
2023-08-30 10:18:38,990 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'
```

### Which colab and model(s) were you using when the error occurred?

stable_diffusion_inpainting_webui_colab

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

**Comment by camenduru** [comment]
please try with new version

**Comment by wsjhear1984** [comment]
Thank you.
