### ISSUE TITLE
[Bug]: AssertionError when doing Inpaint

### ISSUE THREAD

**Issue by etherealxx** [camenduru/stable-diffusion-webui-colab#477]
### What happened?

Not sure what triggers it. It was working before. txt2img also works as usual
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/64251396/8370bc34-76bd-4d2d-af61-78531036aaa6)
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/64251396/f9fbbc11-0980-4835-807a-4705fc45d711)

### Colab cell output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 1822, in preprocess
    assert isinstance(x, dict)
AssertionError
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/dev9/volatile_concentration_localux_colab.ipynb

(using duchaitenaiart and abyssorangemix3 model from this repo)

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

**Comment by etherealxx** [comment]
problem fixed by pressing the x then reuploading the image
