### ISSUE TITLE
[Bug]: Running the code results in an error

### ISSUE THREAD

**Issue by ninki51** [camenduru/stable-diffusion-webui-colab#479]
### What happened?

Running the script results in an error

### Colab cell output

```shell
Status Legend:
(OK):download completed.
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing gfpgan
Installing clip
Installing open_clip
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 355, in <module>
    prepare_environment()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 291, in prepare_environment
    git_clone(codeformer_repo, repo_dir('CodeFormer'), "CodeFormer", codeformer_commit_hash)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 143, in git_clone
    current_hash = run(f'"{git}" -C "{dir}" rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}").strip()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't determine CodeFormer's hash: c5b4593074ba6214284d6acd5f1719b6c5d739af.
Command: "git" -C "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/CodeFormer" rev-parse HEAD
Error code: 128
stdout: HEAD

stderr: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### Which colab and model(s) were you using when the error occurred?

if not os.path.exists(f"/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP"):
  os.mkdir(f"/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP")
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://openaipublic.azureedge.net/clip/models/b8cca3fd41ae0c99ba7e8951adf17d267cdb84cd88be6f7c2e0eca1737a03836/ViT-L-14.pt -d /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP -o ViT-L-14.pt

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

### If you used HiRes mode when the error occurred, please provide the Hires info

Status Legend:
(OK):download completed.
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing gfpgan
Installing clip
Installing open_clip
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 355, in <module>
    prepare_environment()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 291, in prepare_environment
    git_clone(codeformer_repo, repo_dir('CodeFormer'), "CodeFormer", codeformer_commit_hash)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 143, in git_clone
    current_hash = run(f'"{git}" -C "{dir}" rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}").strip()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't determine CodeFormer's hash: c5b4593074ba6214284d6acd5f1719b6c5d739af.
Command: "git" -C "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/CodeFormer" rev-parse HEAD
Error code: 128
stdout: HEAD

stderr: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by JohnieXu** [comment]
got the same error
