### ISSUE TITLE
[Bug]: I do not know how to use.

### ISSUE THREAD

**Issue by Lihaixiao333** [camenduru/stable-diffusion-webui-colab#484]
### What happened?

Installing rembg
Installing onnxruntime for REMBG extension
Installing pymatting for REMBG extension

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
2023-11-20 15:22:17.847996: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-20 15:22:17.848058: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-20 15:22:17.848097: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-20 15:22:19.567132: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 357, in <module>
    start()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 347, in start
    import webui
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/webui.py", line 25, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 25, in <module>
    from gradio import utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 555, in <module>
    class AsyncRequest:
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 575, in AsyncRequest
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

### Colab cell output

```shell
Installing rembg
Installing onnxruntime for REMBG extension
Installing pymatting for REMBG extension

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
2023-11-20 15:22:17.847996: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-20 15:22:17.848058: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-20 15:22:17.848097: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-20 15:22:19.567132: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 357, in <module>
    start()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 347, in start
    import webui
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/webui.py", line 25, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 25, in <module>
    from gradio import utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 555, in <module>
    class AsyncRequest:
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 575, in AsyncRequest
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
```

### Which colab and model(s) were you using when the error occurred?

https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by Lihaixiao333** [comment]
I am a newbie who wants to give SD a try. I don’t know the code very well and I don’t know how to solve the problem. Can anyone help me?

**Comment by jjajj** [comment]
https://github.com/camenduru/stable-diffusion-webui-colab/issues/481
