### ISSUE TITLE
[Bug]: error

### ISSUE THREAD

**Issue by zhyawy** [camenduru/stable-diffusion-webui-colab#496]
### What happened?

can not work

### Colab cell output

```shell
2024-02-15 14:13:39.650011: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 40, in <module>
    main()
  File "/content/stable-diffusion-webui/launch.py", line 36, in main
    start()
  File "/content/stable-diffusion-webui/modules/launch_utils.py", line 340, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 35, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 339, in <module>
    class AsyncRequest:
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 358, in AsyncRequest
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
```

### Which colab and model(s) were you using when the error occurred?

1.5

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by YuanyuanZhang37** [comment]
same issue, could any one help?

**Comment by YuanyuanZhang37** [comment]
@zhyawy 
try this：!pip install httpx==0.18.0

**Comment by shihuohuo** [comment]
![github_error](https://github.com/camenduru/stable-diffusion-webui-colab/assets/30827855/bde2b191-48e6-425e-bcbc-27bd7eb9b5bd)
I‘ve also met this problem. Even try this：!pip install httpx==0.18.0
