### ISSUE TITLE
[Bug]: what‘s happen，can not work

### ISSUE THREAD

**Issue by firestoneleeGM** [camenduru/stable-diffusion-webui-colab#501]
### What happened?

![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/116102669/af56e84e-9766-4cb9-b104-4528a8429a26)

### Colab cell output

```shell
Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
2024-03-25 11:00:13.672999: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-25 11:00:13.673111: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-25 11:00:13.813702: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-25 11:00:16.449136: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 40, in <module>
    main()
  File "/content/stable-diffusion-webui/launch.py", line 36, in main
    start()
  File "/content/stable-diffusion-webui/modules/launch_utils.py", line 340, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 35, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 339, in <module>
    class AsyncRequest:
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 358, in AsyncRequest
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
```

### Which colab and model(s) were you using when the error occurred?

https://civitai.com/models/6424/chilloutmix

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by qingwufong** [comment]
+1

**Comment by IviSoftware** [comment]
try : !pip install httpx==0.18.0
