### ISSUE TITLE
[Bug]: During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by LibraScorpion** [camenduru/stable-diffusion-webui-colab#512]
### What happened?

/content
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
env: PYTHONDONTWRITEBYTECODE=1
env: TF_CPP_MIN_LOG_LEVEL=1
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
51 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/content/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (file too short): ignored.
--2024-08-23 06:42:35--  https://github.com/camenduru/gperftools/releases/download/v1.0/libtcmalloc_minimal.so.4
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/669786276/620e2e64-be9f-4599-904f-18ee3811e159?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240823%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240823T064236Z&X-Amz-Expires=300&X-Amz-Signature=ac2695e81a7e1e6f6472daf218787d4aae46b645cd40c1f3f90b57e7f3d5cb9e&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=669786276&response-content-disposition=attachment%3B%20filename%3Dlibtcmalloc_minimal.so.4&response-content-type=application%2Foctet-stream [following]
--2024-08-23 06:42:36--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/669786276/620e2e64-be9f-4599-904f-18ee3811e159?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240823%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240823T064236Z&X-Amz-Expires=300&X-Amz-Signature=ac2695e81a7e1e6f6472daf218787d4aae46b645cd40c1f3f90b57e7f3d5cb9e&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=669786276&response-content-disposition=attachment%3B%20filename%3Dlibtcmalloc_minimal.so.4&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 373960 (365K) [application/octet-stream]
Saving to: ‘/content/libtcmalloc_minimal.so.4’

/content/libtcmallo 100%[===================>] 365.20K  --.-KB/s    in 0.02s   

2024-08-23 06:42:36 (15.8 MB/s) - ‘/content/libtcmalloc_minimal.so.4’ saved [373960/373960]

env: LD_PRELOAD=/content/libtcmalloc_minimal.so.4
libcairo2-dev is already the newest version (1.16.0-5ubuntu2).
pkg-config is already the newest version (0.29.2-1ubuntu3).
aria2 is already the newest version (1.36.0-1).
python3-dev is already the newest version (3.10.6-1~22.04.1).
The following packages were automatically installed and are no longer required:
  libbz2-dev libpkgconf3 libreadline-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
unionfs-fuse is already the newest version (1.0-1ubuntu2).
The following packages were automatically installed and are no longer required:
  libbz2-dev libpkgconf3 libreadline-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
mkdir: cannot create directory ‘/content/fused-models’: File exists
mkdir: cannot create directory ‘/content/models’: File exists
mkdir: cannot create directory ‘/content/fused-lora’: File exists
mkdir: cannot create directory ‘/content/lora’: File exists
fuse: failed to access mountpoint /content/fused-models: Transport endpoint is not connected
fuse: failed to access mountpoint /content/fused-lora: Transport endpoint is not connected
/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui
Updating files: 100% (203/203), done.
HEAD is now at 22bcc7be attempted fix for infinite loading for settings that some people experience

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
411fe4|OK  |       0B/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP/ViT-L-14.pt

Status Legend:
(OK):download completed.
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 355, in <module>
    prepare_environment()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 299, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements for Web UI")
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "/usr/bin/python3" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Collecting blendmodes==2022 (from -r requirements_versions.txt (line 1))
  Using cached blendmodes-2022-py3-none-any.whl.metadata (12 kB)
Collecting transformers==4.25.1 (from -r requirements_versions.txt (line 2))
  Using cached transformers-4.25.1-py3-none-any.whl.metadata (93 kB)
Collecting accelerate==0.12.0 (from -r requirements_versions.txt (line 3))
  Using cached accelerate-0.12.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: basicsr==1.4.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements_versions.txt (line 4)) (1.4.2)
Collecting gfpgan==1.3.8 (from -r requirements_versions.txt (line 5))
  Using cached gfpgan-1.3.8-py3-none-any.whl.metadata (12 kB)
Collecting gradio==3.23 (from -r requirements_versions.txt (line 6))
  Using cached gradio-3.23.0-py3-none-any.whl.metadata (14 kB)
Collecting numpy==1.23.3 (from -r requirements_versions.txt (line 7))
  Using cached numpy-1.23.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow==9.4.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements_versions.txt (line 8)) (9.4.0)
Collecting realesrgan==0.3.0 (from -r requirements_versions.txt (line 9))
  Using cached realesrgan-0.3.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from -r requirements_versions.txt (line 10)) (2.0.0+cu118)
Collecting omegaconf==2.2.3 (from -r requirements_versions.txt (line 11))
  Using cached omegaconf-2.2.3-py3-none-any.whl.metadata (3.9 kB)
Collecting pytorch_lightning==1.9.4 (from -r requirements_versions.txt (line 12))
  Using cached pytorch_lightning-1.9.4-py3-none-any.whl.metadata (22 kB)
Collecting scikit-image==0.19.2 (from -r requirements_versions.txt (line 13))
  Using cached scikit_image-0.19.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting fonts (from -r requirements_versions.txt (line 14))
  Using cached fonts-0.0.3-py3-none-any.whl.metadata (1.7 kB)
Collecting font-roboto (from -r requirements_versions.txt (line 15))
  Using cached font-roboto-0.0.1.tar.gz (2.4 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting timm==0.6.7 (from -r requirements_versions.txt (line 16))
  Using cached timm-0.6.7-py3-none-any.whl.metadata (33 kB)
Collecting piexif==1.1.3 (from -r requirements_versions.txt (line 17))
  Using cached piexif-1.1.3-py2.py3-none-any.whl.metadata (3.7 kB)
Collecting einops==0.4.1 (from -r requirements_versions.txt (line 18))
  Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting jsonmerge==1.8.0 (from -r requirements_versions.txt (line 19))
  Using cached jsonmerge-1.8.0.tar.gz (26 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting clean-fid==0.1.29 (from -r requirements_versions.txt (line 20))
  Using cached clean_fid-0.1.29-py3-none-any.whl.metadata (36 kB)
Collecting resize-right==0.0.2 (from -r requirements_versions.txt (line 21))
  Using cached resize_right-0.0.2-py3-none-any.whl.metadata (551 bytes)
Collecting torchdiffeq==0.2.3 (from -r requirements_versions.txt (line 22))
  Using cached torchdiffeq-0.2.3-py3-none-any.whl.metadata (488 bytes)
Collecting kornia==0.6.7 (from -r requirements_versions.txt (line 23))
  Using cached kornia-0.6.7-py2.py3-none-any.whl.metadata (12 kB)
Collecting lark==1.1.2 (from -r requirements_versions.txt (line 24))
  Using cached lark-1.1.2-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting inflection==0.5.1 (from -r requirements_versions.txt (line 25))
  Using cached inflection-0.5.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting GitPython==3.1.30 (from -r requirements_versions.txt (line 26))
  Using cached GitPython-3.1.30-py3-none-any.whl.metadata (1.3 kB)
Collecting torchsde==0.2.5 (from -r requirements_versions.txt (line 27))
  Using cached torchsde-0.2.5-py3-none-any.whl.metadata (748 bytes)

stderr: WARNING: Ignoring version 0.2.5 of torchsde since it has invalid metadata:
Requested torchsde==0.2.5 from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl (from -r requirements_versions.txt (line 27)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement torchsde==0.2.5 (from versions: 0.2.5, 0.2.6)
ERROR: No matching distribution found for torchsde==0.2.5

### Colab cell output

```shell
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI




ControlNet init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.





Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
2024-08-23 06:54:30.427494: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-23 06:54:30.469936: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-23 06:54:30.483022: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-23 06:54:31.600138: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 357, in <module>
    start()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 347, in start
    import webui
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/webui.py", line 25, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 25, in <module>
    from gradio import utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 555, in <module>
    class AsyncRequest:
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 575, in AsyncRequest
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
```


### Which colab and model(s) were you using when the error occurred?

Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI




ControlNet init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.





Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
2024-08-23 06:54:30.427494: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-23 06:54:30.469936: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-23 06:54:30.483022: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-23 06:54:31.600138: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 357, in <module>
    start()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py", line 347, in start
    import webui
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/webui.py", line 25, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 25, in <module>
    from gradio import utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 555, in <module>
    class AsyncRequest:
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 575, in AsyncRequest
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

### If you used HiRes mode when the error occurred, please provide the Hires info

_No response_

**Comment by whenold** [comment]
same question
