### ISSUE TITLE
Deforum not working with v2.0 

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#65]
```py
Rerolling with +1 seed failed for 10 iterations! Try setting webui's precision to 'full' and if it fails, please report this to the devs! Interrupting...
Deforum progress:  23% 275/1215 [00:46<02:39,  5.88it/s]
/content/stable-diffusion-webui/outputs/img2img-images/Deforum/20230131183507_%05d.png -> /content/stable-diffusion-webui/outputs/img2img-images/Deforum/20230131183507.mp4
b"ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 / 56. 31.100\n  libavcodec     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\n[image2 @ 0x55e294dd0000] Could find no file with path '/content/stable-diffusion-webui/outputs/img2img-images/Deforum/20230131183507_%05d.png' and index in the range 0-4\n/content/stable-diffusion-webui/outputs/img2img-images/Deforum/20230131183507_%05d.png: No such file or directory\n"
Error completing request
Arguments: ('task(k88yeg7xw0rcmni)', None, False, '', '2D', 120, 'replicate', '0:(0)', '0:(1.02+0.02*sin(2*3.14*t/20))', '0:(0)', '0:(0)', '0:(10)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(t%15)', '0:(0)', '0:(53)', '0: (0.08)', '0: (0.6)', '0: (1.0)', '0: (7)', False, '0: (25)', '0: (70)', '0: (200)', '0: (10000)', '0:(5), 1:(-1), 219:(-1), 220:(5)', False, '0: ("Euler a")', '0: ("!({everywhere}^({init_mask}|{video_mask}) ) ")', False, '0: ("!({everywhere}^({init_mask}|{video_mask}) ) ")', False, '0: ("model1.ckpt"), 100: ("model2.ckpt")', '0: (5)', '0: (1.0)', '0: (0.1)', '0: (0.0)', False, 'Match Frame 0 LAB', 1.0, 1.0, 'perlin', 8.0, 8.0, 4, 0.5, True, 0.3, 'border', 'bicubic', False, '/content/video_in.mp4', 1, 0, -1, False, False, '/content/video_in.mp4', False, '20220829210106', '{\n    "0": "(scenic countryside:1.0), (cherry:`where(cos(6.28*t/10)>0, 1.8*cos(6.28*t/10), 0.001)`), (strawberry:`where(cos(6.28*t/10)<0, -1.8*cos(6.28*t/10), 0.001)`), snow, detailed painting by greg rutkowski --neg (cherry:`where(cos(6.28*t/10)<0, -1.8*cos(6.28*t/10), 0.001)`), (strawberry:`where(cos(6.28*t/10)>0, 1.8*cos(6.28*t/10), 0.001)`)",\n    "60": "a beautiful (((banana))), trending on Artstation",\n    "80": "a beautiful coconut --neg photo, realistic",\n    "100": "a beautiful durian, trending on Artstation"\n    }\n    ', 512, 512, False, -1, 'Euler a', False, -1, 0, 0, 0, 25, 0.0, 1, True, True, False, False, False, 'Deforum', '{timestring}_{index}_{prompt}.png', 'iter', 1, False, False, True, 0, 'https://github.com/hithereai/d/releases/download/m/kaba.png', False, False, False, True, 'https://github.com/hithereai/d/releases/download/m/mask.jpg', 1.0, 1.0, 5.0, 1, True, 4, 'reroll', False, 12.0, 'FFMPEG mp4', 'ffmpeg', 17.0, 'veryslow', 'None', 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_1MB_MP3.mp3', False, False, 200.0, 'x0_pred', '/content/drive/MyDrive/AI/StableDiffusion/2022-09/20220903000939_%05d.png', '/content/drive/MyDrive/AI/StableDiffusion/content/drive/MyDrive/AI/StableDiffusion/2022-09/kabachuha/2022-09/20220903000939.mp4', False, 'RIFE v4.6', 'Disabled', 'Disabled', False, '', True, False, 'None', False, 'None', 'Farneback', False, 'None', False, 'None', False, False, '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://user-images.githubusercontent.com/121192995/215279228-1673df8a-f919-4380-b04c-19379b2041ff.png",\n    "50": "https://user-images.githubusercontent.com/121192995/215279281-7989fd6f-4b9b-4d90-9887-b7960edd59f8.png",\n    "100": "https://user-images.githubusercontent.com/121192995/215279284-afc14543-d220-4142-bbf4-503776ca2b8b.png",\n    "150": "https://user-images.githubusercontent.com/121192995/215279286-23378635-85b3-4457-b248-23e62c048049.jpg",\n    "200": "https://user-images.githubusercontent.com/121192995/215279228-1673df8a-f919-4380-b04c-19379b2041ff.png"\n}', '0:(.75)', '0:(.35)', '0:(.25)', '0:(20)', '0:(.075)') {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 157, in run_deforum
    raise RuntimeError(stderr)
RuntimeError: b"ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 / 56. 31.100\n  libavcodec     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\n[image2 @ 0x55e294dd0000] Could find no file with path '/content/stable-diffusion-webui/outputs/img2img-images/Deforum/20230131183507_%05d.png' and index in the range 0-4\n/content/stable-diffusion-webui/outputs/img2img-images/Deforum/20230131183507_%05d.png: No such file or directory\n"


```

**Comment by camenduru** [comment]
models are ok wget cant get the all download 😐
