### ISSUE TITLE
Not Able to add safetensor files

### ISSUE THREAD

**Issue by anuragrajput40904** [camenduru/stable-diffusion-webui-colab#85]
![image](https://user-images.githubusercontent.com/56230239/218135188-975361fc-f724-485b-83f7-426c1cdd719c.png)

Error:
![image](https://user-images.githubusercontent.com/56230239/218135279-9bbbef0a-9782-44c6-8122-1e12f31a060b.png)

Loading weights [2700c435] from /content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned.ckpt
Using VAE found similar to selected model: /content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned.vae.pt
Loading VAE weights from: /content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned.vae.pt
Applying xformers cross attention optimization.
tag_autocomplete_helper: Old webui version or unrecognized model shape, using fallback for embedding completion.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://7d6ddb3b621c74e3.gradio.app/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "launch.py", line 331, in <module>
    start()
  File "launch.py", line 308, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 163, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner

**Comment by camenduru** [comment]
maybe we should downgrade fastapi
