### ISSUE TITLE
Cannot add middleware after an application has started

### ISSUE THREAD

**Issue by FujaTyping** [camenduru/stable-diffusion-webui-colab#91]
```
Traceback (most recent call last):
  File "launch.py", line 299, in <module>
    start()
  File "launch.py", line 292, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 163, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started
```

**Comment by camenduru** [comment]
Hi @FujaTyping 👋 please check this 
https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_webui_colab.ipynb
we fixed it yesterday please update your colab
