### ISSUE TITLE
Issue with the image browser fork

### ISSUE THREAD

**Issue by etherealxx** [camenduru/stable-diffusion-webui-colab#95]
### Tested on: v2.0 branch
Steps to reproduce:
- generate an image
- go to image browser
- click send to img2img
<img src="https://user-images.githubusercontent.com/64251396/218333882-dd719da7-4a89-4730-a8f3-4e040bd0a8be.png" alt="x" width="300"/>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 155, in send_image_and_dimensions
    img = image_from_url_text(x)
  File "/content/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 72, in image_from_url_text
    filedata = base64.decodebytes(filedata.encode('utf-8'))
  File "/usr/lib/python3.8/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (49) cannot be 1 more than a multiple of 4
```
weirdly, on different session, the error message is this
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 155, in send_image_and_dimensions
    img = image_from_url_text(x)
  File "/content/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 72, in image_from_url_text
    filedata = base64.decodebytes(filedata.encode('utf-8'))
  File "/usr/lib/python3.8/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

```

**Comment by camenduru** [comment]
please change gradio version and try again maybe gradio 🤔

**Comment by etherealxx** [comment]
idk if you mean upgrade or downgrade. But gradio 3.17.0/3.18.0 breaks everything, i tested.

**Comment by camenduru** [comment]
how about 3.9

**Comment by etherealxx** [comment]
> 

i think v2 has many component that will also breaks on 3.9?

**Comment by camenduru** [comment]
can you get any error from chrome inspect

**Comment by camenduru** [comment]
maybe we should open an issue here https://github.com/gradio-app/gradio/issues

**Comment by camenduru** [comment]
maybe switch to this repo https://github.com/AlUlkesh/stable-diffusion-webui-images-browser

**Comment by etherealxx** [comment]
> maybe switch to this repo https://github.com/AlUlkesh/stable-diffusion-webui-images-browser

just checked right now, it has the same problem

**Comment by camenduru** [comment]
how about this https://github.com/nihedon/sd-webui-images-browser

**Comment by etherealxx** [comment]
> https://github.com/AlUlkesh/stable-diffusion-webui-images-browser this one working

ah yes, my bad, that one works fine. I was also checking with the non forked colab, it was a bit laggy, but yeah. works fine.
